### ISSUE TITLE
X9E: model select edit issue on the radio

### ISSUE THREAD

**Issue by Gerold68** [EdgeTX/edgetx#2951] opened 2022-12-27 13:19 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If I copy an active model on the radio, the cursor jumps to slot 60. Even if I navigate then to slot x, the model will be created on slot 60. Moving the model from slot 60 to slot x works.

### Expected Behavior

Model should be created on the slot navigated to.

### Steps To Reproduce

1. Long press on active model
2. select "copy"
3. selection jumps to slot 60
4. move cursor to any slot and press ok
5. model does not appear at chosen slot
6. scrolling the the end of the list, shows model on slot 60.

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X9E / X9E Hall

**Comment by pfeerick** [comment] 2023-12-06 02:41
I believe this may have been related to the issue resolved in #426, and can't reproduce this on a recent Companion+Simulator build.

**Closed by pfeerick** 2023-12-06 02:41 UTC
Labels: bug 🪲, triage
