### ISSUE TITLE
Switch Hardware List Out of Sequence

### ISSUE THREAD

**Issue by jmxp69** [EdgeTX/edgetx#736] opened 2021-09-16 04:17 UTC
Hardware list isn't quite right. 
![screen-2021-09-16-001110](https://user-images.githubusercontent.com/378637/133548425-ae8a25e0-60fc-4e22-ac82-2001fd959bd1.jpg)

![screen-2021-09-16-001558](https://user-images.githubusercontent.com/378637/133548572-e61f038b-70bd-440e-a233-fbb310ea3b0d.jpg)

**Comment by raphaelcoeffic** [comment] 2021-09-16 06:21
@jmxp69 I'd bet this caused by the `flyskyhallsticks` ;-) Can you please have a look without that option?

**Comment by pfeerick** [comment] 2021-09-16 06:25
I would suggest so also... I'm running essentially a nightly build and without `flyskyhallsticks` and the list is right.

**Comment by rotorman** [comment] 2021-09-16 09:10
Indeed, an issue of FLYSKY_HALL_STICKS option. Here without FLYSKY_HALL_STICKS build option:
![NoFlySky](https://user-images.githubusercontent.com/21011587/133584693-d921c178-6034-4cbc-8010-37d8e84bb630.png)
and here with:
![WithFlySky](https://user-images.githubusercontent.com/21011587/133584709-e51a3bc1-ea77-4416-82ff-1cde2b5bfbb0.png)
Now need to find the line in code where the issue stems from...

**Comment by rotorman** [comment] 2021-09-16 11:45
@jmxp69 Hi John - can you please test this fix out?
As I know, you are liking self-compling, to test this PR, you need to switch to this PR branch, as the code is not yet merged in main (thus just running `git pull` won't fetch you the update). Here are the steps for MSYS2:
```
cd ~/edgetx/edgetx_main
git pull
git checkout EX3_EX4_Bugfix
```

To check that you are in correct branch, run `git branch` - the EX3_EX4_Bugfix should be highlighted.

Then clean the build output dir and rerun the std. CMake and make:
```
cd build_output
rm -rf *
cmake -G "MSYS Makefiles" -DCMAKE_PREFIX_PATH=$HOME/5.12.9/mingw73_64 -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DFLYSKY_HALL_STICKS=YES -DCMAKE_BUILD_TYPE=Release ../
make -j`nproc` firmware
```

Thanks!

**Comment by jmxp69** [comment] 2021-09-16 14:18
Looks good to me. The switches appear correctly in mixer now too. Thanks guys. 

@rotorman git branch does show EX3_EX4 fix highlighted. Should I switch back to main?  Is it git checkout main?

Thank you.

![screen-2021-09-16-101321](https://user-images.githubusercontent.com/378637/133628698-879f2d72-0602-4dc5-b933-a89cde2ea97a.jpg)
![screen-2021-09-16-101316](https://user-images.githubusercontent.com/378637/133628702-f8cc8769-0a60-4fd7-a162-fd92a49484df.jpg)

FYI: I found this today--makes posting screenshots to GH a little easier. https://github.com/Tichau/FileConverter/releases/tag/v1.2.3

**Closed** 2021-09-16 14:47 UTC
Labels: bug, color

**Comment by rotorman** [comment] 2021-09-16 14:48
@jmxp69 John - thank you for testing. The code is merged now, thus yes, please switch back to main branch:
```
git checkout main
git branch
git pull
```
Best,
Risto

**Comment by jmxp69** [comment] 2021-09-16 21:56
Thanks for the fix and help with checking the updates out. Appreciate you all. You're doing amazing work.

**Comment by pfeerick** [comment] 2021-09-16 22:55
If it's `simu`/simulator, as Risto said, just drag and drop as GitHub supports PNG. You can even set Simulator to copy to clipboard instead, so no pesky file if you just want to share it. If it's `.BMP` screenshots from the radio, The simplest way for me on Windows is to (right click, Open With) the "Snip and Sketch" tool  and then just copy to clipboard and paste to GitHub, no file conversion necessary. That looks like a handy tool though.

**Comment by jmxp69** [comment] 2021-09-17 02:40
These are radio screenshots. I didn't check Companion for the error.
