### ISSUE TITLE
Zorro with XJT Lite won’t enter bind mode

### ISSUE THREAD

**Issue by rdockstader** [EdgeTX/edgetx#1899] opened 2022-04-26 02:44 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I have a Radiomaster Zorro ELRS with an FrSky XJT lite module. I’ve set up a new model, disabled internal, and set External to XJT lite, D8. However when I press the bind button, the external module fails to enter bind mode. The indicator light doesn’t show it’s entered bind mode, and no receivers will bind to it. 

### Expected Behavior

External module should enter bind mode and bind to the quad. 

### Steps To Reproduce

1. Create a new model
2. Disable internal module
3. Enable external module, set to XJT Lite, D8
4. But the radio in bind mode. 

### Version

2.7.0

### Transmitter

Radiomaster Zorro

**Comment by pfeerick** [comment] 2022-04-26 08:37
A workaround seems to be to set the module to protocol to D8, then highlight XJTLite, and then select it again, since as soon as you select the module, it gets power-cycled, and will be in the right mode ;)

I can reproduce this with Zorro and XJT Lite. Doing module functionality tests only (i.e. not link test) when set to D16 module lights indicate bind, range check and normal modes correctly. However, setting to D8 or LR12 and it does not do anything, and when setting it back to D16 the module does not bind or range check any more. 

It would appear that when changing modes the module is not power cycling? I noticed this when doing comparison test on OpenTX (which does appear to be working properly when changing modes). OTX appears to be power cycling the module, whereas ETX does not. 

A secondary bug seems to be that sometimes the transmitter will revert to XJT (`TYPE_XJT_PXX1`) rather than XJT Lite (`TYPE_XJT_LITE_PXX2`) - haven't been able to determine exact sequence to reproduce yet - seemed to somewhat be related to going from D8 back to D16.

**Comment by pfeerick** [comment] 2022-04-26 09:48
It looks like following the rabbit hole of why was XJT Lite being changed to XJT lead to the culprit :)

**Comment by rdockstader** [comment] 2022-04-26 14:51
Sounds like you're already well down the path on this one, but I did want to confirm that your workaround works for me as well :)

**Closed** 2022-04-27 00:58 UTC
Labels: bug
