### ISSUE TITLE
Text Overlapped in Telemetry Screen

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#2413] opened 2022-09-29 05:27 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Some Text Overlapped, in both simulator and radio.
![IMG 019](https://user-images.githubusercontent.com/18414861/192946109-2f6f89f0-0915-4a6f-b709-297a25e4e032.png)
![WeChat Image_20220929132227](https://user-images.githubusercontent.com/18414861/192946573-91c4fc95-e92b-42ba-aa74-9926339ec797.jpg)

The discover, delete all, etc. buttons are hard to touch properly, just too close to each other.

### Expected Behavior

Not overlap.

### Steps To Reproduce

Model Settings -> Telemetry page

### Version

Nightly (Please give date/commit below)

### Transmitter

FlySky NV14

**Comment by eshifri** [comment] 2022-09-29 16:37
It is a duplicate of #2254 
The problem exists for vertical screens only and is due to the fact that this screen was not converted to lvgl yet.

**Comment by Eldenroot** [comment] 2022-09-29 19:16
Maybe this should be fixed in 2.8 release? If not many new issues (duplicated) will pop up :(

**Comment by pfeerick** [comment] 2022-09-30 00:07
Duplicate of #2254

**Comment by pfeerick** [comment] 2022-09-30 00:10
@eshifri If you get a chance, can you see if blank a line or two can be inserted just for the portrait screens... i.e move sensors table down. I want to try and do some testing of two other PRs so they get merged in soon so may not have time to play with this as soon as I'd like.

**Closed** 2022-09-30 00:11 UTC
Labels: bug 🪲

**Comment by eshifri** [comment] 2022-09-30 00:13
It is sufficient to use shorter text for vertical screen.
If you prefer an extra line, I can try it later today (hopefully).

**Comment by pfeerick** [comment] 2022-09-30 00:25
Are there other instances where shorter is better though... or is it basically just this instance? As if there are more I have no problem resurrecting that PR as a stopgap ;)

**Comment by richardclli** [comment] 2022-09-30 02:26
Strange that is LVGL should have better flow control to avoid overlapping, maybe this screen is not fully LVGL yet?

**Comment by eshifri** [comment] 2022-09-30 02:27
It is not lvgl-ed at all.
