### ISSUE TITLE
No touch back button on setup widgets screen for top bar or panels

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#459] opened 2021-07-15 23:02 UTC
Tx16s
Rc3
After selecting widgets,  to get out of the page the "touch" back (top left of screen) does nothing, I have to use the physical back button

**Comment by pfeerick** [comment] 2021-07-15 23:48
This is a duplicate of #326

**Closed by pfeerick** 2021-07-15 23:48 UTC
