### ISSUE TITLE
Model labels - non-English symbols are not displayed correctly (export Companion)

### ISSUE THREAD

**Issue by Eldenroot** [EdgeTX/edgetx#4635] opened 2024-02-13 17:49 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

non-English symbols are not displayed and exported correctly

For example try "Oblíbené"

### Expected Behavior

Should be ported and displayed correctly.

### Steps To Reproduce

Companion export model

### Version

2.9.3

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

11 64bit

**Comment by pfeerick** [comment] 2024-02-14 02:56
Duplicate of https://github.com/EdgeTX/edgetx/issues/4603

**Closed by pfeerick** 2024-02-14 02:56 UTC
Labels: bug 🪲, triage
