### ISSUE TITLE
Can't exit "Modules / RX version" modal with return button, only touch 

### ISSUE THREAD

**Issue by jurgelenas** [EdgeTX/edgetx#2031] opened 2022-06-12 07:38 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I can't exit "Modules / RX version" modal with the transmitter physical return button. Only by touch: 

![image0(1)](https://user-images.githubusercontent.com/1081265/173222567-e4fb7c3b-3518-49db-97e3-acb596b33c2f.jpeg)

### Expected Behavior

Modal "Modules / RX version" is closed after return button is pressed

### Steps To Reproduce

-

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment] 2022-06-12 07:47
Correction: you can exit without touch by using the Enter button since the exit button is in focus, but exiting via Return is indeed borked - although it is somewhat by design atm as the alternative was an emergency mode crash, which is less desirable.

**Comment by rotorman** [comment] 2022-06-12 08:13
The touch exit from this dialog "works" also if you click slightly to the left of exit button, but clearly the touch coordinates do not match the displayed Exit button coordinates.

**Comment by gagarinlg** [comment] 2022-06-12 08:20
In main exit via Return works, also via Enter
It das not work not with touching the EXIT button, but with touching outside of the window it works.

**Comment by pfeerick** [comment] 2022-09-19 09:54
Was fixed in #2035

**Closed by pfeerick** 2022-09-19 09:54 UTC
Labels: bug 🪲
