### ISSUE TITLE
Logical switches not saved

### ISSUE THREAD

**Issue by pierrotm777** [EdgeTX/edgetx#3645] opened 2023-06-01 11:29 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The logical switches from L30 to L37 are not saved.
L40 to 47 are saved

### Expected Behavior

When i shut down tmy Tx16s Mk2, these logical switches are not saved.
I use a compiled 2.9 firmware with the 1/6/2023 sources

### Steps To Reproduce

Never saved after power down

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

Windows

**Comment by pierrotm777** [comment] 2023-06-01 11:36
I have found than the issue is when i use the TSwitch widget .
I use 2x8 buttons, with one witch use the L30 to L37 logicals switches and the second witch use the L40 to L47 logicals switchs.
When i open the first 8 buttons that erase the logical switches L30-37.
When i open the second 8 buttons that erase the logical switches L40-47.

**Comment by pfeerick** [comment] 2024-03-05 00:06
@pierrotm777 So are you saying there that the issue is actually a bug in https://github.com/Ziege-One/TSwitch or do you believe there to be an issue in EdgeTX still?

**Comment by pierrotm777** [comment] 2024-05-06 05:18
Sorry, I haven't seen your answer.
I think it's an edgetx issue.
I try to do some new tests this morning.

**Comment by pierrotm777** [comment] 2024-05-06 08:50
I test again to add Logical Switch and L30 to L37 aren't saved after handset power off.
As i understand i need to defined 8 Logical Switch like that:
![TSwitch](https://github.com/EdgeTX/edgetx/assets/8189970/b93593b2-e655-4f2a-89c1-7629fcbd447d)

Thanks for your help !
Pierre

**Comment by pierrotm777** [comment] 2024-05-06 08:51
[TSwitch.zip](https://github.com/EdgeTX/edgetx/files/15218624/TSwitch.zip)

**Comment by pfeerick** [comment] 2024-05-06 08:52
With what version of EdgeTX are you testing?

**Comment by pierrotm777** [comment] 2024-05-06 09:10
Ok, how can i configure and use this widget ?
Do i need to update the libgui.lua library ?

**Comment by 3djc** [comment] 2024-05-06 09:11
Maybe you should see that with said widget author ?

**Comment by pierrotm777** [comment] 2024-05-06 09:20
I have followed this video from the author.
https://www.youtube.com/watch?v=PFdHdTHB5m0

**Comment by pierrotm777** [comment] 2024-05-06 09:31
I test the version 2.10.0 RC4

**Comment by pfeerick** [comment] 2024-05-06 09:40
I don't think that video is correct for the version of the script you are using... it seems it changed to using Sticky switches, and no, I don't thing you add anything yourself, the widget adds anything if it needs to. 

So what is the *actual* problem you have here?

**Comment by pfeerick** [comment] 2024-05-06 10:17
So do you want more than one button to control the channel position. i.e. three buttons could be used to mimic a three position switch? As it is not suited to that in it's current form... it is only good for single channel / momentary controls, as the second parameter is how long it should stay active for on it's own after you press it. i.e. 100ms, 500ms, etc. You would either want some more logic (although you are running out quick as it is consuming 8 logical switches with each instance of the widget) or a widget designed more for that purpose. 

I'll close the issue for now, as from what I can tell, it seems to be either an issue with the widget, or with how to use it. Please do let us know if you get anywhere with this, or a response from the author, as I know you have asked before at https://github.com/Ziege-One/TSwitch/issues/1 but didn't get any reply.

**Closed by pfeerick** 2024-05-06 10:17 UTC
Labels: bug 🪲

**Comment by pierrotm777** [comment] 2024-05-06 10:23
Ok, Thanks you :-)
I need to work on this a bit.
