### ISSUE TITLE
Top bar missing when exiting from Telemetry page.

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#5401] opened 2024-08-07 11:23 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Top bar missing, when exiting from Telemetry page. 

### Expected Behavior

Not the above. Resolved by a power off power on.

### Steps To Reproduce

Exiting from telemetry page.

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12, RadioMaster TX16S / TX16SMK2

### Anything else?

Latest nightly
![screen-2024-08-07-122056](https://github.com/user-attachments/assets/2e28003f-570e-472e-a2dd-4df36334e3f6)

**Comment by philmoz** [comment] 2024-08-07 21:51
Duplicate of #5400

**Closed** 2024-08-07 23:01 UTC
Labels: bug 🪲, triage
