### ISSUE TITLE
Crash on boot after enabling Internal MULTI with external ELRS Module

### ISSUE THREAD

**Issue by CREASE-gum-EAR** [EdgeTX/edgetx#1305] opened 2021-12-28 06:21 UTC
I see previous bugs with the Trainer function involved but nothing like this.

I set the following settings and when I restart the radio it crashes on boot. I did the following:
= set Trainer Port to in model settings to Master/MULTI
= set a Switch to enable the Trainer in Special Functions
= set my Internal Multi to DSM_RX and bind with an external radio
= set the Trainer settings under System
= It all works

I turned my radio off and on boot the radio crashes. To fix it I did the following:
= take the SD card and opened it with EdgeTX Companion to read the models
= Trainer Port in model settings is shown to be set to "Master/SBUS in battery compartment"
= This option is shown greyed out so I assume its an invalid entry for a T16?
= I then change it back to Master/MULTI and put the SD back in the radio but it still crashes on boot.
= I then disable the Internal / MULTI and then it boots fine.

**Conclusion:** Something about having the Internal Multi Module Enabled crashes the boot and on top of that, if the Trainer Port in model settings is set to use the MULTI module it then corrupts it to an invalid setting of "Master/SBUS in battery compartment" somehow. I included the corrupted model6.bin file for your reference.

 - EdgeTX version 2.5.0
 - Jumper T16
 - Aftermarket Internal Multi-Module
 - External ExpressLRS

[model6.zip](https://github.com/EdgeTX/edgetx/files/7783115/model6.zip)

**Comment by raphaelcoeffic** [comment] 2021-12-28 07:39
This is a duplicate of #1239. The fix is included in current nightly and will be in 2.6.0 RC2.

**Closed by raphaelcoeffic** 2021-12-28 07:39 UTC
