### ISSUE TITLE
Pot warnings not properly read from radio in Companion

### ISSUE THREAD

**Issue by ulfhedlund** [EdgeTX/edgetx#1050] opened 2021-11-14 14:32 UTC
The pot warnings set in a RMTX16S radio doesn't gets properly read when models and settings are read from the radio in Companion. They seem to get inverted. I have attached two pair of screen shots to illustrate what happens.

My environment: EdgeTX version 2.5, RadioMaster TX16S, Linux Companion (AppImage 2.5.0-28cdb40-x86_64).

![RMTX16S_1](https://user-images.githubusercontent.com/35467815/141685260-63a4698f-4854-4d7c-961d-c283aefb419d.jpg)
![Companion1](https://user-images.githubusercontent.com/35467815/141684742-5d402540-9c02-4879-9ef7-c71447cfdbf1.jpg)
![RMTX16S_2](https://user-images.githubusercontent.com/35467815/141685262-03bb3760-cb96-40e3-8ab3-58698462d349.jpg)
![Companion2](https://user-images.githubusercontent.com/35467815/141684743-fa7c3cc2-f779-4fe7-9251-2070dedd47a7.jpg)

**Comment by pfeerick** [comment] 2021-11-15 03:58
Confirmed with Companion 2.6, TX16S v2.5.0 firmware. TX12 (B&W radio) _appears_ to be ok.

**Comment by elecpower** [comment] 2021-11-15 19:50
Checked code and Companion does not differentiate between radios except for supported hardware when reading these settings so if as @pfeerick has advised "B&W appears to be ok" and as reported is inverted for TX16S (colorlcd) then suspicion moves to radio side. Can one of you radio experts please check?

**Comment by ulfhedlund** [comment] 2021-11-16 17:57
I can also tested on my X-lite BW radio and that seems to work as expected, so I can confirm what @pfeerick writes.

**Comment by elecpower** [comment] 2021-11-16 20:11
> I also tested on my X-lite BW radio and that seems to work as expected, so I can confirm what @pfeerick writes. The pot warnings seem to get inverted when writing to the TX16S radio from Companion as well. So it's both ways.

Consistency is good ;-)

**Comment by elecpower** [comment] 2021-12-11 20:42
So it would appear it is a bug that was introduced to the radio firmware rather than Companion?
Also if left the way it is then radio to radio conversions on both platforms are going to be affected and the YAML values would have to be interpreted inverse as well. Since the YAML files do not contain the radio that created then more issues.
Too much confusion.

**Comment by raphaelcoeffic** [comment] 2021-12-14 06:42
I might be wrong, but I think this is fixed in latest nightly build.

**Comment by ulfhedlund** [comment] 2021-12-18 09:34
A quick test I just did with a fresh build from today shows there are still problems with the TX16S. It seems the warnings are no longer reversed but they are not correctly transferred to/from radio and Companion, as far as I can tell.

**Closed** 2022-06-07 03:04 UTC
Labels: bug 🪲, companion
