### ISSUE TITLE
#4325 X12S poor sound quality in 2.10

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#4403] opened 2023-12-10 20:37 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

As #4325 X12S poor sound quality. 

### Expected Behavior

Am unable to test 2.10 on the X12S due to the poor sound reproduction on the stereo speakers. I believe if left unchecked for to long will be difficult to the find problem in the future due to LVGL implementation. This has occured from the begining of 2.10 nightlies!!

### Steps To Reproduce

As above

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12

### OS Version

-

### Anything else?

Poor sound on all 2.10 firmwares.

**Comment by pfeerick** [comment] 2023-12-11 00:51
Duplicate of #4325. Please don't open multiple issues for the same problem, comment in that issue if there is further information or wanting to try and bump it.

**Closed by pfeerick** 2023-12-11 00:51 UTC
Labels: bug 🪲, triage
