### ISSUE TITLE
Companion - S1 Knob Switch on FrSky X9 Lite is Non Functioning and Cannot be Assigned

### ISSUE THREAD

**Issue by msun12000** [EdgeTX/edgetx#3592] opened 2023-05-12 13:11 UTC
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

No response to S1 rotary knob in Companion V 2.8.3.

### Expected Behavior

S1 rotary knob should be mapped to be configurable as a channel function.
It works fine in OpenTX Companion V 2.3

### Steps To Reproduce

In "Settings - Settings", choose "Radio Type" as FrSky Taranis X9-lite S
On Mixer tab assign S1 to Channel 5
Simulate and observe no movement on Channel 5

### Version

2.8.2

### Transmitter

FrSky X9 Lite / Lite S

### Operating System (OS)

Windows

### OS Version

Windows 10 Home 22H2

### Anything else?

![image](https://github.com/EdgeTX/edgetx/assets/133366782/b3ac9123-1e39-4809-9d14-0a60851bc21b)

**Comment by pfeerick** [comment] 2023-05-15 05:09
Confirmed - radio is writing it as POT1, Companion is doing S1:
![image](https://github.com/EdgeTX/edgetx/assets/5500713/e1240369-1504-4170-94a4-55f4dcd765a2)

It is consistent across radio and model settings, so just need to verify which is the correct one going forwards. I suspect the radio is wrong since it says S1 on OpenTX Companion also.

**Comment by msun12000** [comment] 2023-05-15 15:16
It may help to know that in EdgeTX Companion, under "Radio Settings - Hardware", S1 was found to be set to "None" whereas in OpenTX Companion, it is correctly assigned to "Pot with Detent". Presumably that is the reason for the issue?
Changing the setting to match doesn't resolve the issue.

**Comment by msun12000** [comment] 2023-09-19 20:49
Issue seems to be resolved in EdgeTX V2.9

**Comment by msun12000** [comment] 2023-09-21 12:40
S1 still remains assigned to "none" and shows up in mixer tab as POT1. The source cannot be assigned as seen in snapshots:
![Screenshot 2023-09-21 133452](https://github.com/EdgeTX/edgetx/assets/133366782/f196836e-b437-4819-bf9a-039801661fea)
![Screenshot 2023-09-21 133616](https://github.com/EdgeTX/edgetx/assets/133366782/c76346c3-91db-49ba-84b5-b2197818a464)

**Comment by elecpower** [comment] 2024-01-28 22:10
Expected to be fixed in v2.10

**Closed** 2024-02-04 05:59 UTC
Labels: bug 🪲, companion, simulator
