### ISSUE TITLE
Companion update function in 2.9.2 does not work in Linux Cinnamon

### ISSUE THREAD

**Issue by dlabrie55** [EdgeTX/edgetx#4424] opened 2023-12-15 19:27 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When Trying to download updates I get the  error... Unable to download Meta Data. Error:6
SSL handshake failed

### Expected Behavior

Multiple updates should download, decompress and install. 

### Steps To Reproduce

1. Open Edge Companion 
2. Click on the Download Components arrow.
3. Error messages occur for all downloads.

### Version

2.9.2

### Transmitter

FrSky X9D+

### Operating System (OS)

Linux

### OS Version

Linux Mint 21.2 Cinnamon

### Anything else?

![Screenshot from 2023-12-15 14-20-19](https://github.com/EdgeTX/edgetx/assets/125928359/8bd0dfab-b471-4bf5-81fe-347bf0bbdf1e)

**Comment by dlabrie55** [comment] 2023-12-18 16:08
After getting advice to download [http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb](https://github.com/EdgeTX/edgetx/issues/url) I was able to download and install all fo the data.

**Comment by pfeerick** [comment] 2024-01-12 06:41
Duplicate of https://github.com/EdgeTX/edgetx/issues/4316

**Closed** 2024-01-14 22:28 UTC
Labels: bug 🪲, companion
