### ISSUE TITLE
output tab

### ISSUE THREAD

**Issue by adirb95** [EdgeTX/edgetx#350] opened 2021-06-26 18:32 UTC
while in the output tab you can see the current channel by moving the sticks while on opentx you could move the sticks and see which channel is moving by moving a specific stick ,would be cool if it was the same in EdgeTX

**Comment by Mantamatt1** [comment] 2021-06-26 18:44
I second that! It is a useful feature to have as when editing you dont know which channel anything is on, especially when some receivers require a different channel order

**Comment by rotorman** [comment] 2021-06-26 18:57
Is this possibly a duplicate of #307 ?

**Comment by adirb95** [comment] 2021-06-26 19:11
> Is this possibly a duplicate of #307 ?

i belive it is lol sorry didnt see it

**Comment by rotorman** [comment] 2021-06-26 21:12
Closing, duplicate of #307.

**Closed by rotorman** 2021-06-26 21:12 UTC
