### ISSUE TITLE
"Hello"-Track played last in row on startup...

### ISSUE THREAD

**Issue by notyourbiz** [EdgeTX/edgetx#1119] opened 2021-11-21 20:54 UTC
On Startup first all the Tracks for Switch-state where played, "Hello"-Track is the last.

Steps to reproduce the behavior: Switching on and off

**Expected behavior**
"Hello"-Track first in Row

**Screenshots**
N/A

**General information**
 - EdgeTX version 2.5 / 2.6
 - Hardware TX16S

**Comment by raphaelcoeffic** [comment] 2021-11-21 21:06
@notyourbiz I think we have this issue already a couple of times :-D It's probably the first thing everyone notices 😅

**Comment by rotorman** [comment] 2021-11-21 21:31
@notyourbiz Thank you for taking the time to file the issue! In this case, the startup sound issue has been already listed in Issue #135. As this is a duplicate of the same issue, I will close it here. Cheers!

**Closed by rotorman** 2021-11-21 21:31 UTC

**Comment by pfeerick** [comment] 2021-11-22 00:03
Duplicate of #135
