### ISSUE TITLE
Repeatable Keyboard Crash

### ISSUE THREAD

**Issue by MervDale** [EdgeTX/edgetx#697] opened 2021-09-10 03:42 UTC
Unfortunately I have found that the keyboard can be crashed on the TX16S in that it requires a power down to get out of the crash.
Top bar widget set to “Text” while editing the text if I didn’t just use the backspace option but instead moved the cursor with my finger and touched the keyboard at the same time while placing the cursor over my edit character I could get the keyboard to drop the top keyboard line and crash,  this is repeatable !

This was found on my Eachine TX16S on the 09-09-21 nightly 

![kbrd crash](https://user-images.githubusercontent.com/30642754/132796172-325f1919-3dc2-4178-964d-77542ffeb0a5.png)

**Comment by pfeerick** [comment] 2021-09-10 06:40
@kevinkoenig You broke it... how does the rest of the line go? 😆 

Seems to be related to widget options... I can also reproduce this on TX16s... seems to be if you hit the keyboard at basically the same time as the edit field it goes bonkers (yes, that is the technical term for it). 

I can go one step further... and get an interesting half-height screen effect... only seems to effect the main screen when it happens - i.e. radio setup and model setup screens go full screen again. 

https://user-images.githubusercontent.com/5500713/132810898-31b97b7e-eec0-4444-bc4b-8b552b53eb1e.mp4

**Comment by MervDale** [comment] 2021-09-10 06:55
You can really screw thing up trying to clear it as you can still bring up the menu and change models after you send it "Bonkers"
![split screens](https://user-images.githubusercontent.com/30642754/132812612-5c8ff5f3-e0d2-48d6-bfe2-2bc4503f73ec.jpg)

**Comment by kevinkoenig** [comment] 2021-09-10 08:19
Let me look at it today

**Comment by kevinkoenig** [comment] 2021-09-10 10:32
I just pushed a PR to libopenui #19 that protects against the craziness that was reported and verified by @pfeerick.  Interesting defect.  Not totally my fault :), as the way the keyboard was originally written, it finds the first full screen window.  It does this just by testing the height and width of the window.  

When the keyboard first comes up, it resizes that window.  In onTouchEnd it redisplays the keyboard, like it should, and it finds a different full screen window, and happily resizes that one too, until it finds the main window.  Once that happens all hell breaks loose.  

The PR in libopenui #19 protects against that by testing if the keyboard is already displayed.  If so, it does nothing!  It is interesting to note that in all other screens I could find on every onTouchEnd event it hides the keyboard first and then redisplays it, which is why it doesn't fail anywhere else.  

Fun stuff.  The PR for libopenui should get pushed quickly. 

I also added support to hide the keyboard (like every other window) in topbar.cpp onTouchEnd.  This makes the code more consistent.  Since it is less critical i just put that in the existing branch that there is an open pr against. Once that gets merged it will clean up the keyboard support.

**Comment by MervDale** [comment] 2021-09-14 13:50
Have you guys managed to fix this crash issue with the latest nightly ? Try as I might i could not get it to crash or repeat any of my above screens

**Comment by kevinkoenig** [comment] 2021-09-14 14:22
The fix for this issue was merged last night.  You should not be able to reproduce it any more

**Comment by rotorman** [comment] 2021-09-14 14:35
@MervDale If that is the case for you, can we close this issue?

**Comment by pfeerick** [comment] 2021-09-14 22:24
My mistake, I didn't link to this to the choicex pr as it was being fixed as part of that. This is indeed fixed.

**Comment by pfeerick** [comment] 2021-09-14 22:26
Fixed by #691

**Closed** 2021-09-14 22:26 UTC
Labels: bug, color, UX-UI

**Comment by kevinkoenig** [comment] 2021-09-18 09:05
I have been looking at this for the past hour.  I know what is happening.  Now just to fix it.  

It turns out the duplication case is really easy.  Just click 4 times in the field on Widget settings.  On the 5th click if you have the mouse x coordinate over the enter key (even though the y is over the text field) it fails.  

Working on it.

Kevin

Sent from Mail for Windows

**Comment by kevinkoenig** [comment] 2021-09-18 09:05
Let me look at it today.
Well that was a fun morning.  I just pushed a PR to libopenui that protects against the crazyness that was reported and verified by Peter.  Interesting defect.  
Not totally my fault 😊
The way the keyboard was originally written, it finds the first full screen window.  It does this just by testing the height and width of the window.  Well when the keyboard first comes up, it resizes that window.  In onTouchEnd it redisplays the keyboard, like it should, and it finds a different full screen window, and happily resizes that one too, until it finds the main window.  Once it finds the MainWindow all hell breaks loose.   
I pushed a PR to libopenui that protects against this case.

Sent from my iPhone


On Sep 10, 2021, at 2:56 AM, MervDale ***@***.***> wrote:
﻿
You can really screw thing up trying to clear it as you can still bring up the menu and change models after you send it "Bonkers"
