### ISSUE TITLE
Curve-Editor does not immediately update x-coordinates

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1284] opened 2021-12-22 13:21 UTC
If one creates a new x/y-curve (e.g. 5-points),  it is clearly not possible to move x2 from -50 to say +10, because x3 is 0, and the curve must remain a mathematical function.

But if yoiu move x3 to say 20, it should be possible to move x2 to +10. But this is not possible, x2 is stuck at the last value of x3 (here: 0). One hast to leave the curve-editor and enter it again. Then it works as expected.
Looks like the give values are not propagated correctly to the curve coordinates.

**Comment by gagarinlg** [comment] 2023-02-26 20:30
@philmoz is this fixed with your changes to the curve edit screen?

**Comment by philmoz** [comment] 2023-02-27 00:31
Should be fixed in 2.8.1

**Comment by pfeerick** [comment] 2023-02-27 00:44
#2972 ended up as a duplicate of this, and fixed in #2973, which will be in 2.9

**Closed by pfeerick** 2023-02-27 00:44 UTC
