### ISSUE TITLE
OMP protocol

### ISSUE THREAD

**Issue by Dave-thirteen** [EdgeTX/edgetx#3514] opened 2023-04-23 06:58 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

On Opentx there is an option in the OMP protocol to allow fine tuning
In EdgeTx there is no fine tune option available.
Using same MPM firmware in both.

Could this be implemented please?

Thanks

Dave.

### Expected Behavior

Tune to be available!

### Steps To Reproduce

Select OMP protocol.

### Version

2.8.2

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by pfeerick** [comment] 2023-04-23 07:00
Duplicate of #2713

**Closed by pfeerick** 2023-04-23 07:00 UTC
Labels: bug 🪲, triage
