### ISSUE TITLE
Editing Curves on "Inputs"-Screen

### ISSUE THREAD

**Issue by notyourbiz** [EdgeTX/edgetx#1120] opened 2021-11-21 21:00 UTC
*Before submitting,  search the open issue if there is already a report of the bug*
i did

**Describe the bug**
When trying to edit a preset Curve on "Input"-sereen, the editor field dissapears by pressing << / - / + / >>

**To Reproduce**
Edit a preset Curve on "Input"-Screen

**Expected behavior**
working function

**Screenshots**
N/A

**General information**
 - EdgeTX version 2.5 / 2.6
 - Hardware TX16S

**Comment by pfeerick** [comment] 2021-11-22 00:06
Thanks for the report. Duplicate of #1087

**Comment by pfeerick** [comment] 2021-11-22 00:06
Duplicate of #1087

**Closed by pfeerick** 2021-11-22 00:06 UTC
