### ISSUE TITLE
Favorite section in Model Select

### ISSUE THREAD

**Issue by Rivelino911** [EdgeTX/edgetx#363] opened 2021-06-27 21:43 UTC
Maybe will be good to have a Favorite section in Model Select.
I have many models but, most usually i fly 4 of them.

**Comment by pfeerick** [comment] 2021-06-27 22:38
I'm going to close this as a duplicate of the discussion in https://github.com/EdgeTX/edgetx/issues/181. Filtering/sorting and favorite model selection as the intended future direction by JimB in that issue.

**Closed by pfeerick** 2021-06-27 22:38 UTC
