### ISSUE TITLE
Spektrum Receiver Warning" Failsafe not set"

### ISSUE THREAD

**Issue by planemann2000** [EdgeTX/edgetx#2368] opened 2022-09-26 15:43 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

On some (not all) of my models using Spektrum receiver, when loading I get a Failsafe not set up on the first screen on 2.8 with current 2.8.0 rc1, also had this warning in the nightly earlier. No failsafe mode button in the Model Setup page.

### Expected Behavior

No Failsafe setup with Spektrum Receivers 

### Steps To Reproduce

On some (not all) of my models using Spektrum receiver, when loading I get a Failsafe not set up on the first screen on 2.8 with current 2.8.0 rc1, also had this warning in the nightly earlier. No failsafe mode button in the Model Setup page.

### Version

Other (Please specify below)

### Transmitter

Other (Please specify below)

### Anything else?

Running Edge 2.8.0 rc1 In a Eachine TX16S Transmitter

**Comment by planemann2000** [comment] 2022-09-26 21:02
This issue will duplicate with Spektrum remote receivers on all my Flex Aura equipped planes.

**Comment by pfeerick** [comment] 2022-09-27 00:36
Can you zip your RADIO and MODELS folders from the radio SD card and attach them here? I'm not able to reproduce this, so need to know more about the configuration in order to see what is going on.

**Comment by planemann2000** [comment] 2022-09-27 00:55
Here are my radio and models folders.

Stan
 

    On Monday, September 26, 2022 at 07:36:28 PM CDT, Peter Feerick ***@***.***> wrote:  
 
 


Can you zip your RADIO and MODELS folders from the radio SD card and attach them here? I'm not able to reproduce this, so need to know more about the configuration in order to see what is going on.

**Comment by pfeerick** [comment] 2022-09-27 01:06
You won't be able to add them via email, GitHub doesn't accept any attachments... will need to drag and drop the file onto the text input area of the issue on GitHub.

**Comment by planemann2000** [comment] 2022-09-27 01:11
OK

Stan
 

    On Monday, September 26, 2022 at 08:06:12 PM CDT, Peter Feerick ***@***.***> wrote:  
 
 


You won't be able to add them via email, GitHub doesn't accept any attachments... will need to drag and drop the file onto the text input area of the issue on GitHub.

**Comment by planemann2000** [comment] 2022-09-27 01:13
[RADIO.zip](https://github.com/EdgeTX/edgetx/files/9650642/RADIO.zip)
[MODELS.zip](https://github.com/EdgeTX/edgetx/files/9650643/MODELS.zip)
This good?

**Comment by pfeerick** [comment] 2022-09-27 01:24
Yup, that worked. I'll have a look at that later today. Thanks :)

**Comment by xxxntwv** [comment] 2022-09-27 13:02
I have experienced the same issue using spektrum receivers.Any model I use that uses the dsm protocol causes the fail safe warning.

**Comment by gagarinlg** [comment] 2022-09-27 18:21
Nice, a Heisenbug

**Comment by tonims1** [comment] 2022-09-27 19:44
I have the same problem with a model v950 wltoys KN protocol.

**Comment by xxxntwv** [comment] 2022-10-05 21:55
Update on this issue,it still occurs on 2.8rc2.when switching from models with Frsky protocol to models using spektrum protocols is when it happens.switching between spektrum models it doesn't occur.

**Comment by Mmcb23** [comment] 2022-10-12 13:54
I don't get the warning, but there is no Failsafe setting in the model setup screen for DSM-based reseivers

**Comment by planemann2000** [comment] 2022-10-12 15:22
When the warning appears, it happens quickly after a switch out of position alert happens and the alert cleared, only on Spektrum Receivers.

**Comment by Mmcb23** [comment] 2022-10-12 15:41
I'm guessing I don't get the warning because I set up the models in Companion, so have Failsafe set. It is visible in the YML file. However, there is no option to set it in the radio.

**Comment by raphaelcoeffic** [comment] 2022-10-12 17:58
Gentlemen, as shown in #2527, it has nothing to do with Spektrum.

The specifics are the following:
- internal MPM
- previous model should have failsafe, but it's not set
- switching to a new model that use the internal MPM, and does not have failsafe settings

What happens is basically that the status info from the previous model/protocol are used to assess the failsafe settings of the new model, which is obviously wrong.

**Comment by pfeerick** [comment] 2022-10-12 21:59
> I don't get the warning, but there is no Failsafe setting in the model setup screen for DSM-based receivers. Same behaviour in Simulator

Also, just FYI, the bug there is on Companions side, because Spektrum doesn't have a transmitter configurable failsafe, it's receiver side only (forward programming receivers are a different matter entirely). However, Companion/simulator can't query the MPM to find out what protocols support failsafe settings, etc, hence why the option is still shown.

**Comment by planemann2000** [comment] 2022-10-12 23:16
I have tried to get the failsafe warning for the past 2 days with no success on either transmitter I have (eachine tx16s nor the radiomaster tx16s, both running 2.8.0 rc2) I haven't used Companion yet. I'm stumped, but I have no problem to work around this issue.

**Comment by pfeerick** [comment] 2022-10-12 23:32
Raphael caught the bug shortly after asking how to repo after we narrowed it down to the internal MPM. Hence the linked PR #https://github.com/EdgeTX/edgetx/pull/2527 which will be shortly merged, and in the next nightly.

**Closed** 2022-10-12 23:33 UTC
Labels: bug 🪲

**Comment by xxxntwv** [comment] 2022-10-15 13:32
This issue appears to be fixed in RC3
