### ISSUE TITLE
Display Trim under Model Setup, Change option behaves like No option.

### ISSUE THREAD

**Issue by SilentZen** [EdgeTX/edgetx#2107] opened 2022-06-30 11:53 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Display Trim under Model Setup
Option No works as expected
Option Yes works as expecting by displaying trim in numerical value.
Option Change works same as No with no numerical value ever showing.

### Expected Behavior

I would expect Change would show numerical value while pressing trim's 

### Steps To Reproduce

Select Change for Display Trim under Model Setup then monitor trims while changing.

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by RJMcInty** [comment] 2022-06-30 15:59
This is a dupe of: https://github.com/EdgeTX/edgetx/issues/2050. Perhaps you could weigh in on that thread on the user scenario for this feature?

**Comment by pfeerick** [comment] 2022-07-01 00:44
Duplicate of #2050

**Closed by pfeerick** 2022-07-01 00:44 UTC
Labels: bug 🪲, triage
