### ISSUE TITLE
Logical Switch does not save / gets scrambled

### ISSUE THREAD

**Issue by TGS78** [EdgeTX/edgetx#5510] opened 2024-09-05 00:26 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I created a few logical switches with involved customizable buttons SW1-SW6.
The test at home was fine, but after I went to my fly spot nothing worked anymore, because some logical switch settings were suddenly messed up, f.e. SW3 becomes ...ehm nothing and SW6 becomes S16, see attached pictures.

It can reproduce this behaviour. The issue appears always when I turn the remote controller off and on.
Strangely enough, this happens only if the customizable buttons are the second AND/OR operant (V2), not if they are first (V1).
And the issue only appears if I use for example SW3↓, but no problem with SW3↑.
I have already cleared the logical switch, rebooted, and recreated it. The strange behaviour still exists.

![LS before](https://github.com/user-attachments/assets/47f5b35d-71a2-4a68-ba5a-661086d06b62)
![LS after](https://github.com/user-attachments/assets/f172bede-4a79-4b55-b0ab-81e4967c194b)

### Expected Behavior

---

### Steps To Reproduce

---

### Version

2.10.4

### Transmitter

Jumper T20 V2

**Comment by philmoz** [comment] 2024-09-05 05:29
I can't reproduce this on my T20V2.

Can you upload your MODELS and RADIO folders (in a ZIP file).

**Comment by TGS78** [comment] 2024-09-05 08:37
affected was L15, L16
Meanwhile created an additional L14 with same settings, this also gets scrambled.
And now it becomes even more strange: created a L40 with same settings, but this works.

[T20V2_LS_CS_Issue.zip](https://github.com/user-attachments/files/16886389/T20V2_LS_CS_Issue.zip)

**Comment by philmoz** [comment] 2024-09-06 04:20
Thanks, I was able to reproduce with your file. Should be fixed by PR 5515.

**Closed** 2024-09-08 23:50 UTC
Labels: bug 🪲, triage
