### ISSUE TITLE
TX16S vers 2.7.0 button function lockout

### ISSUE THREAD

**Issue by P062F** [EdgeTX/edgetx#1879] opened 2022-04-23 05:23 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

***SYS>Version>Modules/RX version***
if at this point, page left or right is pressed prior to entering out, upon entering out all buttons lose function at which point transmitter must be restarted to regain button function

### Expected Behavior

Exit back out and have buttons work as intended.

### Steps To Reproduce

SYS>
PAGE>(x7) or PAGE<
ENTER via jogwheel
PAGE< or PAGE>
ENTER via jogwheel
error should now occur

### Version

2.7.0

### Transmitter

Radiomaster TX16S

### Anything else?

Gen 1 TX16S, Fresh install 2.7.0, tx16s-f79978b, en_us-sara language pack, internal and external modules OFF

**Comment by pfeerick** [comment] 2022-04-23 08:46
Duplicate of https://github.com/EdgeTX/edgetx/issues/1582

**Closed** 2022-04-23 08:46 UTC
Labels: bug, duplicate
