### ISSUE TITLE
Missing Antenna Parameter in Horus X10s

### ISSUE THREAD

**Issue by elekSENDER** [EdgeTX/edgetx#1567] opened 2022-02-06 15:02 UTC
**Describe the bug**
There is no possibilty to change the antenna in the X10s.
Missing in X10s Radio Setting/Hardware and Model Setup.
In Companion this parameter is adjustable.

**To Reproduce**
screenshots from OTX 2.3.14

**Expected behavior**
adjustable antenna parameter in X10s

**Screenshots**
Companion EdgeTX:
![grafik](https://user-images.githubusercontent.com/98912034/152685950-0c146ca7-b243-4ba1-b726-2446aa42b26f.png)
![grafik](https://user-images.githubusercontent.com/98912034/152685906-39a50f6a-df53-480b-ae2b-a620d7ed24fc.png)

EdgeTX 2.6.0
![grafik](https://user-images.githubusercontent.com/98912034/152686117-1d3d50cc-c021-4b38-8cc9-c18cc910018a.png)
![grafik](https://user-images.githubusercontent.com/98912034/152685515-c4e89d55-a81b-48b7-bd6b-e73eefef60d4.png)

OTX 2.3.14
![grafik](https://user-images.githubusercontent.com/98912034/152686883-cf590edf-0e80-48ba-a749-4eef6617020b.png)
![grafik](https://user-images.githubusercontent.com/98912034/152686896-f0f315db-fade-49c3-a675-bbc42d719e4b.png)

**General information**
 - EdgeTX version (2.6.0 x10-338d4d2)
 - Hardware (Frsky Horus X10s)

**Comment by pfeerick** [comment] 2022-02-07 00:40
Duplicate of https://github.com/EdgeTX/edgetx/issues/1185

**Comment by elekSENDER** [comment] 2022-02-07 10:03
ups, haven´t seen that, sorry for double-entry

**Closed** 2022-10-11 11:48 UTC
