### ISSUE TITLE
Edge - about page - wrong year + text not displayed 

### ISSUE THREAD

**Issue by Eldenroot** [EdgeTX/edgetx#2052] opened 2022-06-15 20:14 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

QR code is too big and covers text above it. Moreover the year used in copyright is not correct, it should use the auto var during generating new builds to use the latest year according to the last commit or build date.

### Expected Behavior

2022 year and fully visible text

### Steps To Reproduce

Go to about page

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment] 2022-06-16 07:57
This was fixed about two months ago in #1913 and will be in 2.8.0. It has been subsequently refreshed as part of the LVGL overhaul, but the issue is still resolved. i.e. this is what it currently looks like in a recent PR. 
![image](https://user-images.githubusercontent.com/5500713/174021160-6b7b7522-dbe3-4f6d-87e1-02b851f18f2b.png)

**Closed by pfeerick** 2022-06-16 07:57 UTC
Labels: bug 🪲, triage
