### ISSUE TITLE
Some Touch Buttons Won't Change Color Upon Selection/Activating.

### ISSUE THREAD

**Issue by MuhammadQaisarAli** [EdgeTX/edgetx#1007] opened 2021-11-07 18:08 UTC
Some Touch Buttons Won't Change Color Upon Selection/Activating.

**Video**
https://user-images.githubusercontent.com/45729347/140656547-c6dfbbda-e87c-4b17-9e51-e1410c6c2287.mp4

**General information**
 - EdgeTX version 2.5.
 - Hardware RM TX16S.

**Comment by eshifri** [comment] 2021-11-08 19:31
I believe it was reported already months ago. I spent some time trying to figure out the difference between these buttons and the ones that work - no success. :-)

**Comment by pfeerick** [comment] 2021-11-11 00:30
Duplicate of https://github.com/EdgeTX/edgetx/issues/411

**Comment by gagarinlg** [comment] 2023-02-26 20:20
fixed with #1094 and obsolete by introducing LVGL

**Closed by gagarinlg** 2023-02-26 20:20 UTC
