### ISSUE TITLE
Sort RF protocols of MPMs alphabetically

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx#450] opened 2021-07-14 16:34 UTC
Currently on TX16s internal MPM, the RF protocols are list in a random order in the model setup screen.  It would be more user friendly if the RF protocols were listed in alphbetical order.

**Comment by NemesisXB** [comment] 2021-07-14 16:57
Duplicate of issue #159

**Comment by phileville** [comment] 2021-07-14 17:03
Duplicate

**Closed** 2021-07-14 17:03 UTC
