### ISSUE TITLE
Use internal and external HF module at the same time

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#3364] opened 2023-03-17 11:40 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Horus X10S Express:
If I want to use the internal ISRM and an external MPM IRX4+ at the same time, this is not possible. As soon as the external one is set up and ready for use and then the internal ISRM is activated, the connection to the external MPM is immediately interrupted.

### Expected Behavior

both HF moduls should work at the same time

### Steps To Reproduce

try to use both internal and external HF Moduls

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

**Comment by pfeerick** [comment] 2023-03-17 12:22
Have you actually ever been able to do this on the X10? 

i.e. Due to architectural design choices in OTX which ETX has inherited (but there are efforts to change this entirely) not having treating the two (or more) RF modules completely separately, on the TX16 you can use internal MPM and external MPM together, but you can't use internal MPM and external CRSF (or vice versa). Well, actually you *can*, but only with very specific settings. And the same goes for some other module combinations.

**Comment by MRC3742** [comment] 2023-03-17 17:57
It can be done but requires a mod to disconnect the External Sport line from the internal ISRM.
Either by cutting the trace to ISRM or removing the pin on the internal ISRM.
It's believed to have been done intentionally to block just what your trying to do.

More info in these posts
https://www.rcgroups.com/forums/showpost.php?p=44546553&postcount=17686
https://github.com/opentx/opentx/issues/7181#issuecomment-564418313

Rich

**Comment by ParkerEde** [comment] 2023-03-17 18:26
Ah okay. 
If you remove the Sport pin, can you still flash the internal ISRM module?

**Comment by MRC3742** [comment] 2023-03-18 00:17
Yes - Tested working
Flashing the internal ISRM is unaffected by this mod.

Rich

**Comment by ParkerEde** [comment] 2023-03-19 22:32
@pfeerick should we close here? Or do you think we can do something about it software-wise here?

**Comment by pfeerick** [comment] 2023-03-20 10:44
Yes, I think it is safe to close it. This isn't the first time I've heard of the hardware mod needed for ISRM and SPort line (bypassing frsky's decision to disable *some*  external modules when the internal module is enabled), so there isn't a simple software workaround unfortunately - hardware modification is the only solution.

**Closed by pfeerick** 2023-03-20 10:44 UTC
Labels: bug 🪲

**Comment by anshchawla521** [comment] 2023-06-24 20:46
Hi I have a RadioKing t18 (basically a jumper t18)(I know its not supported officially) and a Radio Master Tx12 (MK2 ELRS version) and on both when I enable the internal module the signal to external module (have tested with PPM and SBUS) gets changed and doesn't follow the rules of the protocol. Why might that be happening as now there is nothing related to Frsky ? and what would be the solution for getting a clean PPM / SBUS signal for the JR bay module.

**Comment by pfeerick** [comment] 2023-06-25 11:04
Because running two interfaces wasn't something really thought of when some of the underlying architecture was designed, weird stuff happens when say MPM and ELRS are both enabled, as they run at different speeds. This PR aims to try and resolve some of that https://github.com/EdgeTX/edgetx/pull/3642. I'm not sure what effect there is on PPM/SBUS.

**Comment by anshchawla521** [comment] 2023-06-25 15:03
Ohh ohkka. Thanks a lot , will look into the mentioned PR

**Comment by ParkerEde** [comment] 2023-12-18 15:28
> It can be done but requires a mod to disconnect the External Sport line from the internal ISRM.
> Either by cutting the trace to ISRM or removing the pin on the internal ISRM.
> It's believed to have been done intentionally to block just what your trying to do.

@anshchawla521 Do you have the possibility to plug an MPM into the ext. module bay of your moded X10ISRM and measure the S.PORT voltage for HIGH level with an oscilloscope or logic analyzer (analog input)?

**Comment by anshchawla521** [comment] 2024-02-09 15:01
@ParkerEde Sry for the late reply but I own a T18 which is very similar to a Jumper T18 , so I dont have the X10ISRM 😓
