### ISSUE TITLE
Bind "Beep" never stops when binding Radiolink and SFHSS - carries on chirping - FrSky protocol Rx's are OK.

### ISSUE THREAD

**Issue by MirlynG** [EdgeTX/edgetx#2263] opened 2022-09-02 18:36 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Brand new TX16s MkII. Flashed with 2.7.1 and MTM 1.3.3.14. 

When binding a Radiolink, or SFHSS Rx, the bind tone continues to chirp. Binding works fine. Chirping does not stop by touching the bind button. You can select another model while it is chirping and it does not stop. If you try to bind another model it does not stop, unless it has a D8/16 Rx when it will continue to chirp until D8/16 Rx has bound. Then it will stop. 
If you select aV761 Rx it will stop when Internal Rf is selected. No need to bind.
The only other way to stop it, is to switch off! On restarting, it has stopped.

I imported everything from MkI TX16s running the same firmware. Did not have the issue on the old Tx. 
Have tried re-flashing both firmwares (Edge and MTM). Also went back to MTM 1.3.3.7. I also flashed today's EdgeTx nightly.
Nothing stopped the problem.

### Expected Behavior

Binding tone expected to stop after when bound, on time out or pressing bind button.

### Steps To Reproduce

Select a Radiolink or SFHSS Rx.
Go through bind process. 
Tone does not switch off.
Select new model, with same Rx, does not stop
Select and bind a D8/16Rx and it will stop when bound.
Select a V761 Rx and it stops when the Internal Rf is selected. Do not need to bind with this.

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by shawnholc** [comment] 2022-10-03 04:45
will someone fix this please i have the same issue as well. i flew the airplane like this the other day with the bind beep going on i just turned down the volume some.. and i got a few low signal reports and i was less than 100m away. using TX16S MKII EdgeTX and latest 4in1, Radiolink R8FM with Radiolink BYME-A flight controller. beep, beep, beep! beep, beep, beep!

**Comment by pfeerick** [comment] 2022-10-03 04:54
Ok, I can reproduce this at last, as the RM WT01 (wireless trainer) supports Futaba / SFHSS. Binding beep keeps going regardless of bind completion, and doesn't stop if you press the bind button making it inactive.

**Comment by pfeerick** [comment] 2022-10-03 05:00
>  i got a few low signal reports and i was less than 100m away.

Make sure you've done the RF tune for your MPM - both SFHSS and Radiolink use the CC2500 and thus show the RF Freq fine tune option for calibration. 

https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Frequency_Tuning.md

**Comment by shawnholc** [comment] 2022-10-03 05:37
yea, i did that after i was losing signal, and it really didnt help much. the beep, beep, beep was still there nothing to fix that unless someone fixes the "bug"

**Comment by pfeerick** [comment] 2022-10-03 07:09
That won't fix the beep, but it should fix the range unless the MPM is incorrectly in bind mode or something.

**Comment by raphaelcoeffic** [comment] 2022-10-03 07:11
@pfeerick is that the same on current `main` / `2.8`?

**Comment by raphaelcoeffic** [comment] 2022-10-03 07:30
This happens when the MPM does not detect the end of the binding. Possibly some protocol do not send anything when binding ended properly. It seems the UI code was not resetting the MPM binding status properly, only the general one.

**Comment by shawnholc** [comment] 2022-10-03 07:45
so how do i download the new version? sorry im a noob.

**Comment by MirlynG** [comment] 2022-10-03 07:49
I would not be inclined to download the current release candidate of 2.8 yet. It has way too many issues that need resolving yet! Better to just put up with it until 2.8 is more stable.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shawnholc** [comment] 2022-10-03 09:19
i went ahead and flashed it, works good. just need to click bind again once its bound up.. is it possible to get this fix in 2.7.1?
this version is pretty strange..

**Comment by gagarinlg** [comment] 2022-10-03 09:21
No more 2.7 releases. 2.8 will be out soon.

**Comment by pfeerick** [comment] 2022-10-03 09:23
However, the fix is pretty simple, so you could just add it to 2.7.1 yourself and build a custom build if you want that. 

Do you actually need to press the bind button in the first place... I'm not familiar with Futaba SFHSS, but the info and guides I've seen so far say it is an auto-bind protocol - i.e. you turn the transmitter on, and you press the bind button on the RX, and it just binds. No need to press bind on the transmiter side at all.

**Comment by shawnholc** [comment] 2022-10-03 09:28
hmmm... pretty sure i had to press the bind button... let me check.. yea you have to press bind button

**Comment by shawnholc** [comment] 2022-10-03 09:29
anyhow, thank you for fixing it for us.

**Comment by pfeerick** [comment] 2022-10-03 09:49
Thank you to you both for reporting it, and also for testing the fix :)

**Comment by MirlynG** [comment] 2022-10-03 13:31
> However, the fix is pretty simple, so you could just add it to 2.7.1 yourself and build a custom build if you want that.
> 
Thanks for the help guys, as ever but unsure how this works. Do I just copy the relevant tx16s.bin file from the [edgetx-firmware-merge] zip file to my sd card and flash it or is the process more complicated? Does the commando8-20169b3.bin file have to be flashed as well?

**Comment by gagarinlg** [comment] 2022-10-03 13:32
If you have a TX16S, copy the TX16S file to your SD card and flash it.
As always, make a backup of your SD card first, to have a way back.

**Comment by MirlynG** [comment] 2022-10-03 14:18
Great. Thank you so much.

**Comment by shawnholc** [comment] 2022-10-04 10:03
how do you add the fix to the 2.7.1 and make a custom build?

**Comment by MirlynG** [comment] 2022-10-04 11:03
See gagarinig's post above.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MirlynG** [comment] 2022-10-04 12:46
> how do you add the fix to the 2.7.1 and make a custom build?

Check out my last post and the response posted by "gagarinlg" above.
Here's the zip file download link: https://github.com/EdgeTX/edgetx/suites/8580596495/artifacts/384199955

**Comment by shawnholc** [comment] 2022-10-05 08:40
i did that buy it put 2.8 on my radio.

**Comment by MirlynG** [comment] 2022-10-05 18:45
> i did that but it put 2.8 on my radio.
Yeah. Did that to me too. Anybody have a way around this?

**Comment by shawnholc** [comment] 2022-10-05 20:09
i used to compile blender 3d several years ago, but i forgot most of it.

**Comment by pfeerick** [comment] 2022-10-06 10:02
I could do it for you, but I would prefer to help you fish for yourself... since most of the work has been done so you *can* build it yourself quite easily ;)

So have a look at this: https://github.com/EdgeTX/edgetx/wiki/Building-radio-firmware-in-a-webbrowser-with-Gitpod

There is a written guide as well as a video. 

You'll have a web-based code editor - you can make changes to the source before you build the files - so make the relevant fixes from https://github.com/EdgeTX/edgetx/pull/2455  - i.e. if you are using TX16, you don't need anything except the colorlcd change. Or the relevant b&w fix if using a b&w radio - there you just need the right screen size. 

Since I'm pretty sure you want 2.7, the catch will be there have been a lot of changes to this part of the code, so I would suggest you want to make the change needed for colorlcd in model_setup.cpp at around line L1088 ;) 

If you want to give it a try and get stuck, yell out ;)

**Closed** 2022-10-06 10:03 UTC
Labels: bug 🪲
