### ISSUE TITLE
EM when 'Telem Mirror' selected

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#296] opened 2021-06-21 16:45 UTC
1. Go to RADIO -> HARDWARE
2. Select 'Telem Mirror' in either Serial Port or Serial Port 2

**General information**
- EdgeTX version 2.4.0 RC2
- TX16S

**Comment by raphaelcoeffic** [comment] 2021-06-22 11:11
@JimB40 I will need some more details. For now I cannot reproduce.

Here is what I tried:
- external module OFF: all settings for Serial/Serial2
- external module ON (CRSF): all settings for Serial/Serial2

So far, not crash, reboot, EM or anything like that.

**Comment by raphaelcoeffic** [comment] 2021-06-22 18:40
Fixed by 53261ad067e6f7 & c2908e67d236f565faa2

**Closed by raphaelcoeffic** 2021-06-22 18:40 UTC
Labels: bug

**Comment by JimB40** [comment] 2021-06-23 13:45
Still EM in 1e73101a.
When 'Telem Mirror' selected in both serials

**Comment by JimB40** [comment] 2021-06-23 13:56
Okay tested with latest 68cb9c2. seems to be gone. don't re-open
