### ISSUE TITLE
Frsky X9D+ SE 2019 doesn't start with 2.8rc4

### ISSUE THREAD

**Issue by Luznatural** [EdgeTX/edgetx#2689] opened 2022-11-07 09:24 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I flashed my Frsky X9D+ SE 2019 with ETX 2.8RC4 via SD card, by introducing in the card the latest version of the SD software and placing the firmware in the adequate folder (FIRMWARE).
First flashing the bootloader and after starting in bootloader mode flashing the firmware to the radio. Once finished, selected exit.
Resulted in the radio turning off the display, but remaining the blue light of the switch on. Then the radio didn't respond at all. The only way to re-start the radio was to remove the batery to completely turn off the radio. Once inserting the batery, the radio was unable to start in normal mode, but responded turning on in bootloader mode (presing inwards the trims and turning on). Radio responded to USB connection with the computer.
Checked again the correct 2.8Rc4 firmware (X9DP2019-035e761.bin) tried to flash again from bootloader mode, with same results.
I recovered the radio to ETX 2.7.1 via the previous version of the SDCard, flashing the radio with ETX 2.7.1 from 2.8 bootloader mode, and after re-starting flashing the bootloader to 2.7.1
Tried two more times with same results, even downloading again all files from the web.

### Expected Behavior

Be able to flash the radio as expected.

### Steps To Reproduce

1. Copy the latest version (2.8) to the SD Card
2. Add the 2.8 RC4 firmware to the firmware folder
3. Flash the bootloader to 2.8RC4
4. Start in bootloader mode (presing inwards the trims and turning on) and flash the firmware to the radio
5. When finished, press exit

### Version

Other (Please specify below)

### Transmitter

FrSky X9D+2019

**Comment by pfeerick** [comment] 2022-11-07 09:51
Try doing a DFU flash - that should work... this has been an intermittent problem that seems to arise every so often and were going to investigate after 2.8.0 released, as it seems to be solely related to flashing via the bootloader.

**Comment by pfeerick** [comment] 2022-11-07 09:52
Duplicate of https://github.com/EdgeTX/edgetx/issues/2633

**Comment by Luznatural** [comment] 2022-11-08 09:54
I have been trying to flash the X9DP SE 2019 radio both with **Companion 2.8** and with **EdgeTX Flasher** (advanced flash) without success.
The radio connects to the computer, as the green light of the switch turns on (with the radio off). Selecting the correct file, and trying to flash, in both programs the message "Flashing Complete" takes less than half a second to appear. When you turn on the radio, you continue with ETX 2.7.1.
The radio receives updates correctly using Companion 2.7.1 with 2.7.1 firmware. I have even tried to write 2.8rc4 firmware using companion 2.7.1 and aparently it works, but the radio is locked in the same way than using the bootloader flash.
I doubled checked the correct and most updated USB zadig driver.
I have also tried selecting "force unprotect" in the DFU options. Same results.
I am afraid that this might be something bigger than a problem with the bootloader.

**Comment by pfeerick** [comment] 2022-11-08 10:00
> trying to flash, in both programs the message "Flashing Complete" takes less than half a second to appear. When you turn on the radio, you continue with ETX 2.7.1.

Something is very wrong there - it should take somewhere probably about 15-20 seconds to flash... that's as if it's not even in DFU mode :-/ 

Maybe try https://buddy.edgetx.org in a Chrome based web-browser?

**Comment by Luznatural** [comment] 2022-11-09 10:02
Finally, I was able to install it via Companion 2.8 using a different fresh notebook with Windows 11 on it. (Might there be a possible conflict with previous versions of companion? I do not mind, as once I update the version of firmware, I delete the previous versions)
Nevertheless, we need to fix the Bootloader issue, as is the preferred way of updating for most of the people (at least on my club).
Thanks for the help!!

**Comment by pfeerick** [comment] 2022-11-09 10:22
> Might there be a possible conflict with previous versions of companion? 

There shouldn't be - each version of Companion installs into a separate folder and can work side by side with earlier and later versions. More likely some DFU driver issue. May be worth trying the ImpulseRC Driver fixer if you have issues on that machine again - https://impulserc.com/pages/downloads

> Nevertheless, we need to fix the Bootloader issue,

Indeed, it will be looked into soon.

**Comment by driedeker** [comment] 2022-11-28 20:06
same eror when I flashed with companion 2.8 bricked till i used the stm32 cube software to fix. that on a x9d
+2019 se version.

**Comment by pfeerick** [comment] 2022-11-29 07:03
Should also be able to use EdgeTX Buddy with the radio in DFU mode (i.e. plug in the USB with the radio turned off and leave it off until the flash is complete).

I flashed v2.7.1 via DFU, and then upgraded the bootloader via firmware, and firmware via bootloader. Rather than crash on powerup like it would sometimes do before, strange slured sounds and radio seems to somewhat work. Something is clearly still wrong. I read back with the following settings as STM32CubeProgrammer indicated 1MB of flash... zip file contains the firmware file that was flashed, and what was read back. 

![image](https://user-images.githubusercontent.com/5500713/204461148-43301c81-5274-4fd0-9a80-a131b0adabc7.png)


[x9d+2019_readback.zip](https://github.com/EdgeTX/edgetx/files/10110516/x9d%2B2019_readback.zip)

**Comment by pfeerick** [comment] 2022-11-29 08:48
Something is indeed offset here, and starts exactly at 00080000 in the file... i.e. SPS is seven lines higher down when I look at the readback... 
![image](https://user-images.githubusercontent.com/5500713/204481580-c0125d2b-d245-4066-871f-ef355798fabd.png)
![image](https://user-images.githubusercontent.com/5500713/204482007-de4207d6-7ed0-430e-a689-629a06da4aaa.png)

**Comment by Luznatural** [comment] 2022-11-29 21:43
I have another input, that might be related ti this issue:

I uploaded my X9Dp Se 2019 to ETX 2.8 firmware through companion 2.8,  and all went well in theory.

But then I noticed that in the Sys/Hardware menú, all the inventory was empty, that means that all switches, slides, pots, etc, went blank. I had (---) in all the configuration inventory.

So, all the mixes, sounds, and values didn't work when I activated the correspondant switch, pot or slider.

I had to reintroduce all the configuration manually. Then everything worked again.

I repeated the process and happened every time I upgrade the radio from 2.7.1 to 2.8 the configuration inventory of the radio goes blank.

**Comment by pfeerick** [comment] 2022-11-30 01:12
Just to be 100% clear ... are you saying that (1) was blank? As it is normal for (2) to be blank as that is the custom naming for that control. 

![image](https://user-images.githubusercontent.com/5500713/204683196-e911ae6e-15f7-4508-98d0-6d79d7252392.png)

**Comment by Luznatural** [comment] 2022-11-30 05:40
All in "1" was blank. So, the system didn't react until knowing what was where. When I introduced the description, then everything started working.

**Comment by RoGoR1** [comment] 2022-11-30 16:42
Running Debian 11 (I haven't had windows since the early 2000nds). I have tried everything on my Tarnis x9dp2019, I have edgetx 8.0 boot loader, installed, and had 7.1 initially with all combinations. I tried flashing via companion 2.8.0 and 2.7.1 from the 2.7.1 boot loader, as well as 8.0 boot loader. There is no combination that works for me, I get the same results in all circumstances. I have no problem reverting to 2.7.1, that works no matter what, every time. 

I don't know that there is really anything to gain by upgrading with this radio. I have two joystick models and one quad model elrs 3.0 that works with all of my quads, and everything kind of works. So I'll just stay with 2.7.1. Honestly for this radio, opentx was working just fine too. It's a lot of unnecessary upgrading, but I like to see the cool stuff you're all doing.

**Comment by Luznatural** [comment] 2022-11-30 17:06
I had the same problem with my Windows computer and my X9d+ SE 2019, and solve it in one computer just installing the newest zadig driver. Since then, the Companion 2.8 update works fine for me, with the exception already mentioned before.
The rest of the update procedures caused the same simthops than yours.
You could try that for Debian 11.


-------- Mensaje original --------
De: RoGoR1 ***@***.***>
Fecha: 30/11/22 17:42 (GMT+01:00)
Para: EdgeTX/edgetx ***@***.***>
Cc: Luznatural ***@***.***>, Author ***@***.***>
Asunto: Re: [EdgeTX/edgetx] Frsky X9D+ SE 2019 doesn't start with 2.8rc4 (Issue #2689)


Running Debian 11 (I haven't had windows since the early 2000nds). I have tried everything on my Tarnis x9dp2019, I have edgetx 8.0 boot loader, installed, and had 7.1 initially with all combinations. I tried flashing via companion 2.8.0 and 2.7.1 from the 2.7.1 boot loader, as well as 8.0 boot loader. There is no combination that works for me, I get the same results in all circumstances. I have no problem reverting to 2.7.1, that works no matter what, every time.

I don't know that there is really anything to gain by upgrading with this radio. I have two joystick models and one quad model elrs 3.0 that works with all of my quads, and everything kind of works. So I'll just stay with 2.7.1. Honestly for this radio, opentx was working just fine too. It's a lot of unnecessary upgrading, but I like to see the cool stuff you're all doing.

**Comment by raphaelcoeffic** [comment] 2022-12-10 08:18
@pfeerick I believe this is because you read 1MB instead of 512KB (real size of flash). Seems what you're seeing is the same flash, *again*. (`0x80000` = `512 x 1014`)

**Comment by pfeerick** [comment] 2022-12-13 01:59
So STM32Cube is fibbing when it says 1MB flash size? *Nevermind... I see reports that it does sometimes lie* 🤦 

![image](https://user-images.githubusercontent.com/5500713/207204936-bb91175a-e9e6-4c1f-a9a6-0583cd350d34.png)

What's more annoying/confusing is DFU is reporting the same sizes for X9D+, X9D+2019 and Zorro (i.e. 1M total) ... ah, but not for the TX16S.
```
C:\Users\pfeer>dfu-util -l
X9D+
Found DFU: [0483:df11] ver=2200, devnum=15, cfg=1, intf=0, alt=0, name="@Internal Flash  /0x08000000/04*016Kg,01*064Kg,07*128Kg", serial="386A396B3138"

X9D+2019
Found DFU: [0483:df11] ver=2200, devnum=16, cfg=1, intf=0, alt=0, name="@Internal Flash  /0x08000000/04*016Kg,01*064Kg,07*128Kg", serial="3982366E3039"

Zorro
Found DFU: [0483:df11] ver=2200, devnum=17, cfg=1, intf=0, alt=0, name="@Internal Flash  /0x08000000/04*016Kg,01*064Kg,07*128Kg", serial="358532703131"

TX16S
Found DFU: [0483:df11] ver=2200, devnum=18, cfg=1, intf=0, alt=0, name="@Internal Flash  /0x08000000/04*016Kg,01*064Kg,07*128Kg,04*016Kg,01*064Kg,07*128Kg", serial="367D346D3439"
```

**Comment by roberted9** [comment] 2022-12-19 02:19
> ### Is there an existing issue for this problem?
> * [x]  I have searched the existing issues
> 
> ### What part of EdgeTX is the focus of this bug?
> Transmitter firmware
> 
> ### Current Behavior
> I flashed my Frsky X9D+ SE 2019 with ETX 2.8RC4 via SD card, by introducing in the card the latest version of the SD software and placing the firmware in the adequate folder (FIRMWARE). First flashing the bootloader and after starting in bootloader mode flashing the firmware to the radio. Once finished, selected exit. Resulted in the radio turning off the display, but remaining the blue light of the switch on. Then the radio didn't respond at all. The only way to re-start the radio was to remove the batery to completely turn off the radio. Once inserting the batery, the radio was unable to start in normal mode, but responded turning on in bootloader mode (presing inwards the trims and turning on). Radio responded to USB connection with the computer. Checked again the correct 2.8Rc4 firmware (X9DP2019-035e761.bin) tried to flash again from bootloader mode, with same results. I recovered the radio to ETX 2.7.1 via the previous version of the SDCard, flashing the radio with ETX 2.7.1 from 2.8 bootloader mode, and after re-starting flashing the bootloader to 2.7.1 Tried two more times with same results, even downloading again all files from the web.
> 
> ### Expected Behavior
> Be able to flash the radio as expected.
> 
> ### Steps To Reproduce
> 1. Copy the latest version (2.8) to the SD Card
> 2. Add the 2.8 RC4 firmware to the firmware folder
> 3. Flash the bootloader to 2.8RC4
> 4. Start in bootloader mode (presing inwards the trims and turning on) and flash the firmware to the radio
> 5. When finished, press exit
> 
> ### Version
> Other (Please specify below)
> 
> ### Transmitter
> FrSky X9D+2019
> 
> ### Anything else?
> _No response_

I'm having the same problem using 9XD+ SE 2019 and iMac.
 

I can flash 2.7.1 and get the firmware and flashed bootloader but I get opentx sounds.
Welcome to opentx as Edgetx appears on my screen??

**Comment by pfeerick** [comment] 2022-12-19 03:08
@roberted9 Sounds come from the SD card, so if you haven't updated the SD card pack/sounds with the EdgeTX ones, then you only have the OpenTX sounds, hence they get played ;) 

i.e. you need (latest/2.8 versions of both SD card pack  and sound pack will work fine with 2.7)
https://github.com/EdgeTX/edgetx-sdcard/releases/tag/v2.8.0 (bw212x64.zip for X9D widescreen B&W)
https://github.com/EdgeTX/edgetx-sdcard-sounds/releases/tag/v2.8.0

**Comment by roberted9** [comment] 2022-12-19 05:42
Got edgetx  2.7.1 with voice working,.
  Thanks
   Robert

**Comment by roberted9** [comment] 2022-12-19 06:23
Hello,
 I have all my models and settings but none of my Crossfire nano receivers were bound and betaflight lauscripts doesn’t work.
 It says downloading board information for 5 minutes and it used to take less than 30 seconds.
  Is there problems using Taranis 9XD+ 2019 radios with edgetx?
   Thanks,
  Robert

**Comment by pfeerick** [comment] 2022-12-19 09:06
Crossfire RXs shouldn't loose their bind due to a ETX update - the bind is between the Crossfire module and the RX... the only thing EdgeTX can do to influence that is have the wrong baudrate for the Ext. RF/CRSF (should be 400k) or the wrong model id. 

The downloading board information is suggestive of either the wrong version of the betaflight Lua, or again the baud rate is wrong since the info needs to come through the Crossfire module.(also double check that RADIO/SYS -> Hardware -> Sample Mode is set to OneBit). Other than that, it may be better to take this to [Discord](https://discord.gg/wF9wUKnZ6H) as this isn't related to the issue at hand.

**Comment by F0undling** [comment] 2023-01-03 06:43
Hi Everyone, I am new to this so thank you for making me feel like i am not going insane. I was wondering if anyone else is having an issue binding their receivers? I have tried updating their firmware on my RX8R as when i previously tried to bind it I only got both green and red like constant. Which Dr. Google and a youtube video tells me the firmware wasn't correct. Has anyone else had this issue? 

Cheers

**Comment by FrankDrebin88** [comment] 2023-01-07 17:31
Hi to all. Any news for flashing edge tx2.8 with sd and bootloader? i ve tried but i ve encountered the same issue.

**Comment by Slibs** [comment] 2023-02-01 22:36
Can someone point me to a SW or a tutorial on how to unbrick the radio?

**Comment by roberted9** [comment] 2023-02-02 04:38
There’s a few videos on YouTube.JB does one.
 One way is remove battery and SDcard.Turn on radio with no SDcard and see what happens.

**Comment by pfeerick** [comment] 2023-02-19 07:05
This shouldn't be an issue as of 2.8.1 - an undetected firmware overflow. Neither my X9D+ or X9D+2019 have had bootloader firmware issues since the fixes were applied, and I was also able to update to 2.8.1 without issue (via bootloader). Please let us know if you still have any problems! :)

**Closed by pfeerick** 2023-02-19 07:05 UTC
Labels: bug 🪲
