### ISSUE TITLE
nirvana NV14 flysky brick

### ISSUE THREAD

**Issue by yhomega** [EdgeTX/edgetx#1531] opened 2022-01-31 13:48 UTC
Hello! today I decided to switch to edge tx from open tx

I tried to flash edge tx using https://buddy.edgetx.org/ on my NV14.
2.5 works fine but 2.6 doesn't. It brick my radio (blackscreen, no boot) I have to flash 2.5 with buddy otherwise radio is useless.

I tried using the sdcard method : select firmware in SD card, reboot, with T4 and T1 centered.
No success again, blackscreen, no boot. This time I just have to remove the battery and I can boot my nirvana on firmware 2.5 without having to reflash

My nirvana is few months old, it has power mod from factory.

I saw other method of flashing, please let me know if I should try (opentx companion or  STM32CubeProgrammer)

facebook topic https://www.facebook.com/groups/edgetx/posts/3087681718228665/
Cheers

**Comment by eshifri** [comment] 2022-02-01 02:17
I would say that flashing from the SD card is a very reliable way to do it.

**Comment by pfeerick** [comment] 2022-02-01 02:48
As long as you are flashing the NV14 firmware, I'm not sure what is going on here... i.e. double check after you select the firmware via the bootloader menu that it says "radio: nv14" at the bottom of the screen. However, I have just spotted an unrelated bug in relation to trimhat navigation in the 2.6.0 bootloader :-/

**Comment by stefan73** [comment] 2022-02-01 12:57
Additional thought: Some older FWs for the Nirvana hat partially unreliable flashing SW in the bootloader. If flashed via SD afaik the bootloader is not updated. I would recommend to update the radio to EdgeTX via DFU once.

**Comment by yhomega** [comment] 2022-02-01 13:49
Thanks for the answer, so stefan73 you recommend to flash using "STM32CubeProgrammer " or "opentx companion"? Using the buddy edgetx it's also DFU!

Pfeerick and Eshifri : When using the SD card version, I can't get to bootloader. It "bricks" just before that.

actually I just did some more testing, and I can get to bootloader with 2.5 and 2.6 rc1
With 2.6 rc2, rc3, nightly and 2.6 santa I get black screen, no bootloader, and I have to remove battery in order to boot the radio again.

**Comment by eshifri** [comment] 2022-02-01 18:10
If you can flash the 2.6RC1 FW through DFU you will get the working bootloader.
Now you can flash any other version from SD card - it will not overwrite the bootloader. (And your bootloader will be "good enough" :-) )
Now you can experiment with other FW versions.
As pfeerick has suggested the first thing to do is to check that you are flashing the NV14 version.

**Comment by yhomega** [comment] 2022-02-01 19:37
Eshifri, I just flash RC1 with edgetx buddy through DFU, It worked fined
Then I flash 2.6 from SD with RC1 bootloader, it bricks the nirvana.

**Comment by stefan73** [comment] 2022-02-01 20:25
Just retried. Flashed the old FW and then back to EdgeTX. Works.
Are you using old SD card contents? - Try with a fresh setup SD from here: https://github.com/EdgeTX/edgetx-sdcard/releases

**Comment by yhomega** [comment] 2022-02-01 21:06
yes I did format my sd and used the edgetx sdcard thing

I also tried rc1 with edgetx buddy, then 2.6 with edgetx buddy, brick also

**Comment by gagarinlg** [comment] 2022-02-05 09:58
Can you please send a picture of the mainboardand zip of your sdcard? I have two different hardware versions here and both work with the 2.6 release.

**Comment by yhomega** [comment] 2022-02-05 10:46
https://photos.app.goo.gl/SEGFWQTMFMP37r86A photos I did when I received the nirvana few months ago. Some sort of Power mod was done from factory. For the sdcard I format it before installing edgetx. Can't provide a zip right now

**Comment by yhomega** [comment] 2022-02-05 11:35
https://drive.google.com/file/d/1annH4WoD3M2fWzGG1BBMeYaqvx0MlNoa/view?usp=sharing here is the zip of the sdcard

**Comment by gagarinlg** [comment] 2022-02-05 12:56
Thank you, I will take a look, if there is anything obvious

**Comment by yhomega** [comment] 2022-02-05 13:14
The zip is from sd 2.5 but I tried with sd 2.6 and same issue

**Comment by yhomega** [comment] 2022-02-05 13:16
It's definitly something done on edgetx after rc1. Because 2.5 and 2.6 rc1 work fine.

**Comment by gagarinlg** [comment] 2022-02-05 14:02
> It's definitly something done on edgetx after rc1. Because 2.5 and 2.6 rc1 work fine.

I tried tried your sd card content with 2.6 on both NV14 I have, and both work.
Which country do you llive in?

**Comment by yhomega** [comment] 2022-02-05 14:11
france, NV14 was ordered on aliexpress

**Comment by gagarinlg** [comment] 2022-02-05 14:34
> france, NV14 was ordered on aliexpress

I do not know of a developer living in france, but some are living in Germany. If you are close enought to the broder, maybe something can be arranged, if nobody else is able to reproduce the problem.

**Comment by yhomega** [comment] 2022-02-05 14:56
I will have to ship it to germany or an other country... if I can avoid this. Would you like a video? Or I do some sort of debugging maybe? Meanwhile you recommend me to stick to 2.5 or 2.6 rc1? You saw the pictures of my hardware. Yours is similar with power mod from factory? It could be the issue maybe?!

**Comment by gagarinlg** [comment] 2022-02-05 15:04
> I will have to ship it to germany or an other country... if I can avoid this. Would you like a video? Or I do some sort of debugging maybe? Meanwhile you recommend me to stick to 2.5 or 2.6 rc1? You saw the pictures of my hardware. Yours is similar with power mod from factory? It could be the issue maybe?!

Do you have access to a SWD debugger, ST-Link or something similar? A video probably wouldn't help much.
Both of my NV14s look different. One has a much newer main PCB, the other one has the same as you have PCB, but the wiring looks different. 
I'll take a look at a diff between rc1 and 2.6, maybe I can spot something.

**Comment by yhomega** [comment] 2022-02-05 15:15
I must have a ST link somewhere, just can't find it right now.
How hard is it to use it on the nirvana? 
CHeers

**Comment by gagarinlg** [comment] 2022-02-05 15:27
You have to find the pads for SWCLK, SWDIO, NRST, MCU_3_3V and GND and solder a cable on them. Attached as a picture of one of my NV14. The other one is closed currently.
![photo_2022-02-05_16-25-00](https://user-images.githubusercontent.com/54738901/152647962-6fe632b8-4e63-4010-b7c9-cff7c32b9e30.jpg)
.

**Comment by gagarinlg** [comment] 2022-02-05 15:30
In the diff between RC1 and 2.6 release I found nothing obvious regarding NV14, that could break stuff like that.

**Comment by rotorman** [comment] 2022-02-05 16:15
One hint about ST-Link. If you do not have the original ST-Link (looks like this: https://www.st.com/bin/ecommerce/api/image.PF251168.en.feature-description-include-personalized-no-cpn-large.jpg ) and have a clone, you might want to omit connecting the +3.3V line. The reason is that orignal ST-Link uses this to set the voltage levels, it is a reference input for the ST-Link. Numerous clones output +3.3V on that line. It would be then multiple voltage regulators operating on the same line, which is not good.

**Comment by yhomega** [comment] 2022-02-05 16:20
thanks, I have a race tomorrow, I will try to do it on tuesday/wednesday. What should I do after connection?

**Comment by yhomega** [comment] 2022-02-16 08:29
Any recommendation after the stlink is connected? I just try to update again or something else? Cheers

**Comment by rotorman** [comment] 2022-02-16 08:42
First test would be if STM32CubeProgrammer detects the microcontroller at all. If so, then the good news is that the microcontroller is still alive. You can next erase the chip and flash EdgeTX NV14 binary with STM32CubeProgrammer via SWD.

**Comment by yhomega** [comment] 2022-03-20 14:19
ok I did it but exactly the same problem as flashing with edgetx buddy or the sdcar
![flash 2 6](https://user-images.githubusercontent.com/14169296/159166887-a753e4d5-61fc-45a1-84f3-3b36ca70a51c.JPG)
d

**Comment by rotorman** [comment] 2022-03-20 14:24
The STM32CubeProgrammer is happy in your case - verify successful. Can you enter EdgeTX bootloader at least with your NV14?

**Comment by yhomega** [comment] 2022-03-20 14:33
yes like previously

**Comment by yhomega** [comment] 2022-03-20 14:36
Im about to remove the stlink wires inside and just give up. Anythink else I can do?
I think I will get a new nirvana. gagarinlg does your nV14 with v2.2 motherboard needs some sort of powermod or any other mod to work properly? (Removing pull-up on S.PORT line?)

thanks

**Comment by gagarinlg** [comment] 2022-03-20 14:39
> Im about to remove the stlink wires inside and just give up. Anythink else I can do? I think I will get a new nirvana. gagarinlg does your nV14 with v2.2 motherboard needs some sort of powermod or any other mod to work properly? (Removing pull-up on S.PORT line?)
> 
> thanks

I never really did anything with it except debugging. I connected the MPM externaly and short after the voltage regulator died. Ever since I only used it for debugging and applying 3.3V from the inside.

**Comment by rotorman** [comment] 2022-03-20 14:53
@yhomega as you can enter bootloader, the display and the connection works, so the issue is just that the main firmware for some unknown reason does not display anything on your display. Rename on SD card \RADIO to \RADIO_bck and \MODELS to \MODELS_bck and remove any custom splash or themes, if you have installed any. Does this help?

As you have ST-Link attached, you could try to let the code run in in-circuit-debug mode by stepping through the initialization and see where on earth it hangs in your case.

**Comment by gagarinlg** [comment] 2022-03-20 14:57
If you are able to debug, please try to check which display controller you have by stepping the the coder in targets/nv4/lcd_driver.cpp

**Comment by yhomega** [comment] 2022-03-20 16:18
thanks for the inputs but I have no idea how to debug and I have already removed st link wires. I ordered an other nv14 and will send the faulty one back

**Comment by rotorman** [comment] 2022-03-20 16:21
Hmm... but you said it worked with EdgeTX 2.5 w/o issues, so it might not be a hw problem?

**Comment by yhomega** [comment] 2022-03-20 16:22
so what's the problem? everybody is able to flash 2.6 Im the only one having issue

**Comment by yhomega** [comment] 2022-03-20 16:23
its not just a display issue. the nv14 brick once I flash 2.6
the screen very slightly turn brightness on, but on/off don't work, only removing the battery work

**Comment by yhomega** [comment] 2022-03-20 16:24
2.6 rc1 did work, but not above

**Comment by eshifri** [comment] 2022-03-20 17:42
Did we change the display driver between 2.6RC1 and RC2?

**Comment by rotorman** [comment] 2022-03-20 18:38
This is the last change to NV14 display driver on Dec. 26th, 2021: https://github.com/EdgeTX/edgetx/commit/a1e03ed7b5745609134f4425e68fdbbf573233c5

**Comment by gagarinlg** [comment] 2022-03-20 19:02
There was a change to fix one display type.
Maybe it would help to put change line 1344
  } else if (LCD_ST7796S_ReadID() == LCD_ST7796S_ID) {
  to
  } else {
and remove the unknown lcd controller block, but why does the bootloader work? it uses the same code

**Comment by gagarinlg** [comment] 2022-03-20 19:15
@yhomega can you please try the attached build? You have to unpack it before flashing.

[firmware.zip](https://github.com/EdgeTX/edgetx/files/8311989/firmware.zip)

**Comment by yhomega** [comment] 2022-03-20 19:55
yes it works thanks. I should keep it?

**Comment by gagarinlg** [comment] 2022-03-20 20:16
If you like. This is the current development state plus the fix
It will be fixed in 2.7

**Closed** 2022-03-21 00:37 UTC

**Comment by gagarinlg** [comment] 2022-03-21 06:44
@yhomega it is in the nightlies now.
Thx @pfeerick

**Comment by yhomega** [comment] 2022-03-21 11:08
thank you very much I will enjoy expresslrs/edgetx fast communication :)
regarding sdcard, I can use the content from 2.5?
cheers

**Comment by gagarinlg** [comment] 2022-03-21 11:17
Themes have a different format. The radio and model settings will be converted to Yaml.

**Comment by yhomega** [comment] 2022-03-21 11:24
For themes it's not an issue I don't use them.
For radio and model setting, conversion is automatic or I have something to do?

**Comment by gagarinlg** [comment] 2022-03-21 11:26
Should be automatic. If you need any help, join the discord server at https://discord.gg/wF9wUKnZ6H
