### ISSUE TITLE
Inputs Source Max in Companion is Changed During Write to Radio

### ISSUE THREAD

**Issue by jmxp69** [EdgeTX/edgetx#758] opened 2021-09-18 20:09 UTC
2.5.0 (514796fa) flyskyhallsticks, noheli + standard make options

When setting source to MAX in an Input on Companion, after writing models/settings to radio, the source is changed to "0" in the Source line of the input editor. It shows as JSx (Pot) in the Inputs list. When I change from JSx (Pot) to a switch like SB, the radio reverts to Emergency Mode. This is repeatable. 

![image](https://user-images.githubusercontent.com/378637/133907293-da48d74c-5ffa-4dbc-a04a-944917302dbf.png)

When I read the same model from radio into Companion, the source shown is CYC.

**Comment by jmxp69** [comment] 2021-09-19 04:12
https://youtu.be/rGhFryQ_tC0

**Comment by raphaelcoeffic** [comment] 2021-09-19 08:30
@jmxp69 does this include any radio interaction? what do you mean with "after writing models/settings to radio"?
Regarding the source being different on radio and companion, this could be caused by the extra sources added for the `flyskyhallsticks`, which Companion does not know about. I think we have an issue with the storage model in this case. @rotorman I think the extra sources break the storage format in some way. I believe a model stored with `flyskyhallsticks` is different when read on a radio with a firmware that does not have that option. This is probably an issue for companion.

**Comment by elecpower** [comment] 2021-09-19 08:46
Even when 100% yaml still need to be able to map settings between eeprom and yaml radios.

**Comment by elecpower** [comment] 2021-09-19 08:50
If extra sources added, this has likely offset every source above so the ripple effect will show up in many lists.

**Comment by raphaelcoeffic** [comment] 2021-09-19 08:59
> If extra sources added, this has likely offset every source above so the ripple effect will show up in many lists/places.

Yes, but this is a "special compilation option" that is not available by default. We need confirmation, but I think it makes sense to declare it as "known issue" until we have a real solution to it. Otherwise, this will end up in a new binary format conversion. This is much too late in the game for introducing a new one.

**Comment by pfeerick** [comment] 2021-09-19 12:13
PR#761 being merged means the next nightly *should* work properly for you with Companion ;) Feel free to yell, scream and stomp if it doesn't :)

**Closed by pfeerick** 2021-09-19 12:13 UTC
Labels: bug, companion

**Comment by jmxp69** [comment] 2021-09-19 21:24
761 cured the translation between Companion and Radio *so far*. I need to do some deep inspection to make sure. 

On the radio, if I set the input source to MAX, then read the models in from Companion, Companion would show CYC2 per the picture.
On Companion, if I set the input source to MAX, then pushed the models/settings via Companion to the radio, the radio would show the odd JSx for input source.

If I changed JSx to a switch, the radio goes into Emergency Mode and after rebooting, the input source remained JSx.
If I changed JSx to MAX, no reboot, and the input source remained MAX until I read it by Companion and which point Companion would show CYC2 again.

**Comment by jmxp69** [comment] 2021-09-19 21:25
FYI This little gem pushed Widgets too. So when widgets were setup correctly on the radio a read/write cycle from Companion changed every widget by two spaces. Widget sources were changed forcing manual modification of widget source to -2 on every one.

**Comment by raphaelcoeffic** [comment] 2021-09-20 04:20
> FYI This little gem pushed Widgets too. So when widgets were setup correctly on the radio a read/write cycle from Companion changed every widget by two spaces. Widget sources were changed forcing manual modification of widget source to -2 on every one.

The issue is that making `EXT3` and `EXT4` available would shift all the indexes by 2, which is what you observed. And this why we had to take it back (for now).
