### ISSUE TITLE
Receiver ID wont show warning.

### ISSUE THREAD

**Issue by MuhammadQaisarAli** [EdgeTX/edgetx#1052] opened 2021-11-14 17:29 UTC
When we bind a new model, the receiver ID always starts from 0, unlike OpenTx, EdgeTx won't make a warning of an ID, if already being used, which makes it very easy to overwrite the old model receiver ID. Please solve it.

**General information**
 - EdgeTX version: 2.5.
 - Hardware: RM TX16S)

**Comment by pfeerick** [comment] 2021-11-16 01:56
Duplicate of #1053

**Closed by pfeerick** 2021-11-16 01:56 UTC
