### ISSUE TITLE
edgetx 2.9.4 update download installation error

### ISSUE THREAD

**Issue by orstratcat** [EdgeTX/edgetx#4763] opened 2024-03-18 14:29 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When doing  download update in Companion getting this installation error

****No assets found in release 'Multiprotocol v1.3.4.0' using filter '^MultiLuaScripts'
Multiprotocol preparation failed**** 

### Expected Behavior

Update without errors

### Steps To Reproduce

press download button in Companion

### Version

2.9.4

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

win11

**Comment by elecpower** [comment] 2024-03-22 04:52
The latest MPM release almost doubled the number of assets and exceeds the current list limit of 50. The MultiLuaScripts file is not in the first 50.
Will be fixed in 2.10 RC 2 and 2.9.5 (if there is one).
Duplicate of #4773.

**Closed by elecpower** 2024-03-22 04:52 UTC
Labels: bug 🪲, companion

**Comment by Scritz68** [comment] 2024-04-08 08:10
win 10 x64 same error.
thank you for all you do guys n gals 
(hope thats not rude these days im old, never know anyones reactions to saying old sayings lol. be safe all and again Thank you! )

**Comment by elecpower** [comment] 2024-04-08 08:42
Please refer to earlier comment

**Comment by dragonclips** [comment] 2024-05-19 14:37
same issue  W10 x64

**Comment by pfeerick** [comment] 2024-05-19 21:36
Earlier comment still applies => https://github.com/EdgeTX/edgetx/issues/4763#issuecomment-2014351462
