### ISSUE TITLE
FlySky AFHDS2A telemetry  - Problem with FS- CGPS01

### ISSUE THREAD

**Issue by LS-67** [EdgeTX/edgetx#4784] opened 2024-03-21 13:54 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

TX : Radiomaster TX 16S (4 in 1 module) - ETX 2.9.4 - MPM 1.3.4.0
RX : FS IA10B who's connected with FlySky2A, PWM, iBus
After connecting GPS to RX, when i discover new sensor, only one sensor is displayed 
Sensor ID 0040 and a lot of numbers who have no signification for me.
How can I access to latitude/longitude/altitude/speed?
Is this a problem with ETX or with MPM firmware ?

### Expected Behavior

I would like to access to latitude/longitude/altitude/speed.

### Steps To Reproduce

Connect GPS to FS iA10B
Discover new sensor

### Version

2.9.4

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### Anything else?

![GPS](https://github.com/EdgeTX/edgetx/assets/90781575/77dfbf41-f489-49ad-ae52-a23e655c8c96)

**Comment by pfeerick** [comment] 2024-03-22 01:15
Duplicate of https://github.com/EdgeTX/edgetx/issues/3230

**Closed by pfeerick** 2024-03-22 01:15 UTC
Labels: bug 🪲, triage
