### ISSUE TITLE
Cannot use the scroll wheel to modify the Refresh rate of SBUS on External RF

### ISSUE THREAD

**Issue by zyren** [EdgeTX/edgetx#733] opened 2021-09-15 11:23 UTC
Firmware version： today's nightly
When SBUS is selected for External RF, the Refresh rate cannot be modified with the scroll wheel, and the virtual keyboard can be modified with << and >>, but it cannot be modified with +/-.
![image](https://user-images.githubusercontent.com/6081642/133424541-b02cd960-4b77-46db-8fc4-cd2736a61783.png)

**Comment by pfeerick** [comment] 2021-09-15 11:46
What about if you scroll the wheel fast? I can reproduce similar behaviour non-changing if using -/+ on the touch keyboard, but `<<` and `>>` work, probably because they increase the next significant digit. It seems like at certain numbers, you need to scroll the wheel faster to get it to move, but should change (TX16S).

**Comment by zyren** [comment] 2021-09-15 11:55
> What about if you scroll the wheel fast? I can reproduce similar behaviour non-changing if using -/+ on the touch keyboard, but `<<` and `>>` work, probably because they increase the next significant digit. It seems like at certain numbers, you need to scroll the wheel faster to get it to move, but should change (TX16S).
Oh, it is indeed necessary to roll faster, slow speed does not work, the roller I am using is modified according to Risto's enhancement roller board, and all functions are currently normal.
Thank u!

**Comment by pfeerick** [comment] 2021-09-15 12:21
Excellent... at least it's a easily reproducible bug! We like those, usually easier to squash!

**Comment by pfeerick** [comment] 2022-03-22 09:54
This was resolved in #864

**Closed by pfeerick** 2022-03-22 09:54 UTC
Labels: bug, color
