### ISSUE TITLE
SYS/MDL/TELE buttons to be active anywhere in the menu

### ISSUE THREAD

**Issue by JyeSmith** [EdgeTX/edgetx#2039] opened 2022-06-13 08:53 UTC
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Nope. Everything is awesome.

### Describe the solution you'd like

On handsets with SYS/MDL/TELE buttons, when pressed they should take you to their relevant screen regardless of where you are in the menu system.  As of 2.7 you must return to the home screen and then they become active.

### Describe alternatives you've considered

Not flying... because I dont like pressing RTN.

### Additional context

![image](https://user-images.githubusercontent.com/14170229/173316703-11477475-e144-4eb2-afeb-f86fddb5be6c.png)

**Comment by raphaelcoeffic** [comment] 2022-06-13 11:00
Duplicate of #169 

Sorry @JyeSmith, this was already raised ;-) That being said, thx for the "Everything is awesome"!

**Closed** 2022-06-13 11:03 UTC
Labels: enhancement ✨
