### ISSUE TITLE
horus x12s with edgetx 2.9.2

### ISSUE THREAD

**Issue by grafwiloff** [EdgeTX/edgetx#4470] opened 2023-12-27 02:02 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

hi, yi cannot calibrate the little red joystick … :-(
gr Matthias

### Expected Behavior

it has to be calibrated …

### Steps To Reproduce

i miss it on the calibration issue …

### Version

2.9.2

### Transmitter

FrSky X12

### Operating System (OS)

macOS

**Comment by Luznatural** [comment] 2023-12-27 07:34
Repeated. Solving this problem is already on issues #535 Add calibration of analog joystick and #2361 Calibration screen improvements.

**Comment by pfeerick** [comment] 2024-03-04 23:11
Duplicate of https://github.com/EdgeTX/edgetx/issues/535

**Closed by pfeerick** 2024-03-04 23:11 UTC
Labels: bug 🪲, triage
