### ISSUE TITLE
Emergency Mode & Freezing after using back/forward buttons in some screens

### ISSUE THREAD

**Issue by EhAye** [EdgeTX/edgetx#2690] opened 2022-11-07 12:45 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In some screens, using `Page>` / `Page<` does not work correctly, and upon exiting the screen, an Emergency Mode will happen. On some screens the radio will just lock up and not respond, not even the power button.

I first found it while editing telemetry sensors to disable the logging on some sensors, and i tried to use the  `Page>` / `Page<` buttons to go to the next telemetry sensor without having to exit back to the main telemetry screen. (feature request!)

The Page buttons didn't work as expected, and when i hit the `RTN` button, i got an Emergency Mode. I'm able to replicate this issue in several screens:

Emergency Mode :
Telemetry Sensor "edit" screen
Channel Outputs "edit" screen

Complete Lockup:
Curves "edit" screen

I'm sure other sub-screens will do similar, these are the ones I've repeatedly tested and confirmed. It seems to matter how many times you press the Page Buttons. Pressing it once isn't always enough to create the bug. Pressing them 5 or 6 times will surely do it.

### Expected Behavior

Page buttons should not crash the game!

Feature Request: Page buttons should work on sub screens (eg: telemetry settings, output channel settings, etc...) Have them switch to the next channel, or the next telemetry sensor, etc. 

### Steps To Reproduce

1. Create a New Model
2. Open Model Settings, go to the Outputs Screen
3. Edit any of the Outputs
4. Press  `Page>`  5 or 6 times
5. Press `RTN` button

= Emergency Mode

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

EdgeTX 2.8.0 RC3

Very rarely, when it doesn't cause an Emergency Mode, pressing the Back button will back me out into a different screen then i came from.

**Comment by eshifri** [comment] 2022-11-07 17:08
This must be fixed in 2.8.0RC4. Can you please give it a try?

**Comment by raphaelcoeffic** [comment] 2022-11-07 19:36
Yep, this is a duplicate of #2595

**Closed by raphaelcoeffic** 2022-11-07 19:36 UTC
Labels: bug 🪲, triage
