### ISSUE TITLE
NV14 Internal Module is not Usable

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#606] opened 2021-08-20 07:55 UTC
Selecting ADHFS2 will crash the radio.

Seems the ADHFS2 driver is not present.

**General information**
 - EdgeTX main branch nightly
 - Hardware Flysky NV14

**Comment by eshifri** [comment] 2021-08-20 13:47
This is a duplicate of #520

**Comment by pfeerick** [comment] 2021-08-20 22:19
Duplicate of #520

**Closed by pfeerick** 2021-08-20 22:19 UTC
