### ISSUE TITLE
Issues with time resets and not saving settings in time on ZORRO

### ISSUE THREAD

**Issue by zyren** [EdgeTX/edgetx#1588] opened 2022-02-13 05:38 UTC
Suggestions to improve storage on Zorro:

Hardware: Radiomaster ZORRO
Firmware version: EdgeTX2.6.0 Release

- [ ] After just modifying a certain setting, turn off the power immediately and turn it on again. This setting is not saved to the change. I found that after changing a certain setting, I need to use it for a while, or wait for a while, and then will be saved.
- [x] The system time will be reset from time to time. Sometimes it is normal to ON/OFF the radio multiple times. But sometimes the date and time will be reset to 2000 and 00:00:00, and sometimes it will automatically reset to 1970. #1643

**Comment by pfeerick** [comment] 2022-02-13 06:06
1. Can you be more specific - model settings, radio settings? If model settings, any particular page? This does matter as it could related to a specific group of settings and incorrrect save trigger (this exact problem has been fixed a few times in the codebase now. 

2. Interesting, so there could be some sort of glitch reading the RTC... When it read 1970, had you taken the batteries out? I noticed a weird glitch with mine if you take the batteries out, hold the power button down (it flashes for a moment, showing residual power being drained). If you put the batteries back in, year will be 1970 on the first power up, and on the second powerup it will be 2000 (with not manual change). The RTC battery on on this transmitter is still fine though (3.12v) so it's not like that's flat, even though this does seem like the RTC time isn't surviving the main batteries being removed. :-/

**Comment by zyren** [comment] 2022-02-13 07:00
> 1. Can you be more specific - model settings, radio settings? If model settings, any particular page? This does matter as it could related to a specific group of settings and incorrrect save trigger (this exact problem has been fixed a few times in the codebase now).
> 2. Interesting, so there could be some sort of glitch reading the RTC... When it read 1970, had you taken the batteries out? I noticed a weird glitch with mine if you take the batteries out, hold the power button down (it flashes for a moment, showing residual power being drained). If you put the batteries back in, year will be 1970 on the first power up, and on the second powerup it will be 2000 (with not manual change). The RTC battery on on this transmitter is still fine though (3.12v) so it's not like that's flat, even though this does seem like the RTC time isn't surviving the main batteries being removed. :-/

Answering the first question: Yes, I had this problem when I changed the Model name in Model Setup, and also when I changed the Multi protocol, sorry I didn't make it clear and complete before, this phenomenon is Occasional, not every time. But it always happens by accident.

**Comment by gagarinlg** [comment] 2022-02-13 07:07
1. I had similar problems while debugging. It takes a few seconds to trigger the write. I think exiting the respective model/radio setup pages should trigger a write directly.

**Comment by pfeerick** [comment] 2022-02-13 08:09
Oh, interesting... I know with the colorlcd it does... I wonder if the B&W still has as the delay that was used to batch EEPROM writes going on... 

Also, I think you have to leave the page for writing to be triggered... i.e. setting the name and then turning off the transmitter probably won't save if you don't leave the model setup page, or change to the next one...

**Comment by pfeerick** [comment] 2022-02-13 09:01
Hm.. ok... most colorlcd edits trigger write one second after the control is finished with... i.e. you tick the minute call timer checkbox, and a second later it will be written to file. Play musical chairs with a couple of checkboxes (and keep changing them within a second), and a second after you last touch them, it'll be written. And it's been this way the whole time... it's not a recent change. easy enough to see happen on simu as it tells you it's writing to file. There have been a few cases where radio settings are being written instead of model settings, but I thought we had caught all of them - that's why I was wondering if there was anything specific just in case yet another page/control was triggering the wrong save.

**Comment by arhifisyant** [comment] 2022-02-22 14:28
I knew this issue post since a day after the post date #1588 . 
I have sorro also. I face the same problem. Im on nightly build right now. But, I can tell you, since 2.6.0, until the latest nightlybuild, the problem still occur. Im sorry, I cant provide a clue so we can find the culprit. I can only confirm that this problem may common among the owner of zorro

**Comment by zyren** [comment] 2022-02-25 02:07
Newly discovered issues:
Once in DFU mode, even briefly (turn off Radio, plug in USB, unplug USB), the system date is reset to 1970, and the test engineer found that the RTC crystal oscillator would stop pulsing after exiting DFU

**Comment by pfeerick** [comment] 2022-02-28 23:45
@zyren I don't think I was able to readily reproduce the first part of this issue... did #1643 fix that for you also, or is that still outstanding?

**Comment by pfeerick** [comment] 2022-03-01 02:30
Thank you very much for that explanation, that makes perfect sense. Given the STM32 is not running directly from a battery, it stands to reason the brownout detector can be used to ensure the MCU only runs once the supply voltage is higher and remains stable. 

I was specifically referring to this first part of the issue... as the RTC issue appears to be completely gone, and I don't want to close this yet if this is still outstanding:
> After just modifying a certain setting, turn off the power immediately and turn it on again. This setting is not saved to the change. I found that after changing a certain setting, I need to use it for a while, or wait for a while, and then will be saved.

**Comment by zyren** [comment] 2022-03-01 02:45
> Thank you very much for that explanation, that makes perfect sense. Given the STM32 is not running directly from a battery, it stands to reason the brownout detector can be used to ensure the MCU only runs once the supply voltage is higher and remains stable.
> 
> I was specifically referring to this first part of the issue... as the RTC issue appears to be completely gone, and I don't want to close this yet if this is still outstanding:
> 
> > After just modifying a certain setting, turn off the power immediately and turn it on again. This setting is not saved to the change. I found that after changing a certain setting, I need to use it for a while, or wait for a while, and then will be saved.

Oh, I haven't reproduced this problem again, maybe my test is not rigorous enough, or maybe the date reset is misleading me. I recalled carefully, maybe I didn't press the ENT key when I changed the model name, because I tried this many times, I changed the model name, pressed the ENT key, immediately shut down, and everything was normal.
 so I doubt that I encountered The problem was that I didn't press the ENT key and didn't confirm the change. I'm so sorry maybe I misremembered and misled you.

**Comment by pfeerick** [comment] 2022-03-01 04:18
Ah, yes, that is quite possible, and I may have also been guilty of that myself :grin: 

I'll close this issue then,  but don't hesitate to open a new one if you catch it happening again and have ruled out user error. There is a delay between settings change and a write being triggered of about 1s, so that could also play some part - i.e. was to try and allow multiple changes to be written in a batch AFAIK to keep EEPROM write cycles down.

**Closed** 2022-03-01 04:19 UTC
Labels: bug

**Comment by Roman-Golod** [comment] 2022-08-05 06:53
I have the same problem with the Radiomaster Zorro ELRS version. Date/time reset every reboot sometimes to 2000, sometimes to 1970 year. EdgeTX 2.7.1 and nightly 2.8.0 the same behavior.

**Comment by pfeerick** [comment] 2022-08-05 07:34
@Roman-Golod I just created an new issue for this as this one is closed since the fix that was thought to resolve this has been in place for the Zorro since 2.7.0 onwards.
