### ISSUE TITLE
Edge TX2.6.0 Companion does not show/maintain custom telemetry screens

### ISSUE THREAD

**Issue by dk7xe** [EdgeTX/edgetx#1614] opened 2022-02-20 11:34 UTC
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**
With ETX2.6.0 / Companion 2.6.0 custom screen maintenance does not work via [Companion](https://github.com/EdgeTX/edgetx/releases/download/v2.6.0/edgetx-cpn-linux-v2.6.0.zip) on Ubuntu 20.4 Linux.
Custom telemetry screen created on FrSky X9D+2019 is not showing up in Companion after loading models and setting. from Radio.
A Telemetry screen created within companion does not show up on the related model on FrSky X9D+2019 after writing Models to Radio.
It looks like this is an issue of Companion 2.6.0 since the YAML file generated on the radio shows the custom telemetry screen values.
It worked before with ETX2.5.0

**To Reproduce**
Flash ETX2.6.0 to Radio.
Create / Maintain a custom screen on a model.
Run Companion 2.6.0
Switch Radio on into boot loader mode and connect to PC.
Within Companion press read model an settings from radio button.
Open the model where custom screen was created/maintained.
Go to Custom screens in Companion and check content --> fields are empty.
Go to a different model that has no custom screen in Companion and set telemetry values to display.
Write model an settings to radio.
Check the related model custom screen --> no entries.

**Expected behavior**
custom screens maintained within ETX on radio should be visible within Companion and vice versa.

**Screenshots**
Telemetry screen of model
![screen-2022-02-20-113350](https://user-images.githubusercontent.com/3907200/154839863-6b883ebb-37b1-48a3-98a9-d9827ae0f1e9.png)
![screen-2022-02-20-113515](https://user-images.githubusercontent.com/3907200/154839864-d356b766-0fe3-4ace-bf6e-bc8d6ea33a7e.png)
Screenshot companion
![Hive_Telemetry](https://user-images.githubusercontent.com/3907200/154839893-c6dc608c-21ea-460c-8b3f-79483e2bcd8c.jpg)

**General information**
 - EdgeTX version 2.6.0
 - Hardware FrSky X9D+2019
 - Edgetx companion edgetx-cpn-linux-v2.6.0.zip 
 
![screen-2022-02-20-112648](https://user-images.githubusercontent.com/3907200/154839780-a9c659d0-9e62-4d64-a936-d39271007b59.png)

YAML File of the related model that shows no custom screen in Companion
[model05.zip](https://github.com/EdgeTX/edgetx/files/8103881/model05.zip)

**Comment by men1al** [comment] 2022-02-20 12:29
Exactly the same here, no custom screens in Companion 2.6:
- X9D+ with EdgeTX 2.6 (x9dp-338d4d2)
- Companion 2.6 Windows (Win11 Pro 21H2)

TX has custom telemetry screens which are working with EdgeTX 2.6, but are not shown by Companion 2.6.

It worked before with TX EdgeTX 2.5 and Companion 2.5 Windows version.

**Comment by pfeerick** [comment] 2022-02-23 01:02
Duplicate of https://github.com/EdgeTX/edgetx/issues/1557

**Comment by dk7xe** [comment] 2022-02-25 11:03
> Duplicate of #1557. Was fixed in #1562 which is and will be included in 2.6.1, which is delayed but will be out soon.

Peter, is there a nightly build of Companion available that can be tested? On https://github.com/EdgeTX/edgetx/releases/ i just see FW for the remote controls under nightly.

**Comment by pfeerick** [comment] 2022-02-26 04:38
No, only PR builds, as companion takes significantly longer to build. And unfortunately the last 2.6 companion branch build expired.

**Comment by pfeerick** [comment] 2022-03-16 11:31
Just a FYI, 2.6.1 is basically scrapped due to delays resulting in 2.7 release getting close, so you'll actually be able to grab companion builds from the main 2.7 branch now... since there has been some work on that... i.e. goto https://github.com/EdgeTX/edgetx/actions and on the left side pick the companion build action for your preferred OS, pick the latest of the builds from the `main` branch - i.e. there was one from three hours ago... and then get the download for under The "Artifacts" headings down the bottom of the page.

**Closed by pfeerick** 2022-03-16 11:31 UTC

**Comment by dk7xe** [comment] 2022-03-23 14:57
Thank you @pfeerick will test edgetx-cpn-linux-main https://github.com/EdgeTX/edgetx/commit/33f761c17b3b7b181c18e6ab2ab71f0670658a5e

**Comment by dk7xe** [comment] 2022-04-04 19:37
@pfeerick Peter i can confirm that with edgetx-cpn-linux-main https://github.com/EdgeTX/edgetx/commit/33f761c17b3b7b181c18e6ab2ab71f0670658a5e the problem has been solved. Custom screen maintenance works as expected.
@men1al fyi
