### ISSUE TITLE
Trim hats/joysticks as menu navigation aids on NV14

### ISSUE THREAD

**Issue by vadimus-ca** [EdgeTX/edgetx#904] opened 2021-10-14 13:29 UTC
Can trim hats be used to help menu navigation on NV14?
Some menu items, especially bottom ones, are really tricky to be hit with a finger, thus either a bigger font (or bigger line spacing) should be used, or some other ways to make it more "clickable"

**Comment by vadimus-ca** [comment] 2021-10-14 15:46
> press of both trimhats to switch into nav mode and a double long press of both to switch back to trim mode?

Ideally, trimhats should be automatically - the scenario when the pilot needs to adjust the trim while changing model settings/using LUA seems a bit strange to me.

**Comment by pfeerick** [comment] 2021-10-14 23:19
This is a duplicate of #622, but the title/focus is clearer on this issue.

**Closed** 2021-11-09 01:50 UTC
Labels: duplicate, enhancement, lua-api
