### ISSUE TITLE
Special/Global Function Repeat Value Selection

### ISSUE THREAD

**Issue by skytra** [EdgeTX/edgetx#1539] opened 2022-02-01 19:40 UTC
- EdgeTX version 2.6.0 338d4d2
 - Hardware Eachine (Radiomaster) TX16S 

When you setup a Global or Special Function with "Play Sound" you can select the Repeat

When you scroll right --> it will end at 60s
When you scroll left <-- it goes 3s, 2s, 1s, 1x, !x1 and jumpes all the way to 60s you can't scroll right you have to scroll "59.... times" left again to get back to 1s or 1x !1x

**Comment by pfeerick** [comment] 2022-02-06 01:08
Duplicate of #491, but admittedly has been somewhat forgotten.

**Closed** 2022-02-06 01:13 UTC
