### ISSUE TITLE
No GHOST MENU on TOOLS

### ISSUE THREAD

**Issue by mizuta1951** [EdgeTX/edgetx#1003] opened 2021-11-07 06:38 UTC
GHOST MENU is  lost in SYS ->TOOLS.
Radio is Radiomaster TX16S.
In OpenTX this menu appeared when using IRC GHOST Module.

**Comment by pfeerick** [comment] 2021-11-07 09:58
Duplicate of #577

**Closed by pfeerick** 2021-11-07 09:58 UTC
Labels: enhancement
