### ISSUE TITLE
Ability to use inactive trims as 3 way switches

### ISSUE THREAD

**Issue by 3djc** [EdgeTX/edgetx#4453] opened 2023-12-22 13:19 UTC
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

when a trim is disabled in FM, it cannot be used as a 'switch source'

### Describe the solution you'd like

Ability to use it. There are questions to be thought through as in essence, that switch wont be always existing, what do we do when it doesnt

### Describe alternatives you've considered

put more mixer lines instead of a simple one

**Comment by philmoz** [comment] 2023-12-22 20:35
Where are you seeing this?
I've been using T5 & T6 as switch sources in my TX16S since 2.8.

**Comment by 3djc** [comment] 2023-12-22 20:39
B&W. Can you do a mix line with a trim switch (NOT the trim channel) a a source ?

**Comment by 3djc** [comment] 2023-12-22 20:45
Just checked, you can use trim channel, like on b&w. I'll give you an example so it is clearer. You want to disable the trim in flight mode, and then use the trim switch as a 3 pos switch to drive a winch a 4x4 car for example. As source it would give 0 untouched, and either -1024 or +1024 depending on the direction

**Comment by pfeerick** [comment] 2023-12-23 00:27
This is basically a duplicate of https://github.com/EdgeTX/edgetx/issues/1741

**Comment by philmoz** [comment] 2023-12-23 03:22
<img width="474" alt="Screenshot 2023-12-23 at 2 21 17 pm" src="https://github.com/EdgeTX/edgetx/assets/9474356/a43c4c82-7eaa-4a95-ab86-6721dfa0e352">

**Comment by philmoz** [comment] 2023-12-23 03:45
Potential fix - radio/src/opentx.cpp, getTrimValue function.

Change:
```c
    if (v.mode == TRIM_MODE_NONE) {
      return result;
    }
```

To:
```c
    if (v.mode == TRIM_MODE_NONE) {
      uint8_t tidx = idx * 2;
      if (trimDown(tidx)) return -1024;
      else if (trimDown(tidx + 1)) return 1024;
      return 0;
    }
```

**Comment by pfeerick** [comment] 2023-12-23 03:53
Yes, you can use a three-line mix, with MAX, 0, and MIN as the sources (i.e. as JC wrote under "Describe alternatives you've considered"), but that isn't anywhere as end-user-friendly as just being able to assign a switch as a source in a single mix line. You just can't use it _directly_ as a source though, which is the focus here... 

And regarding the switch not existing... from a usability standpoint, shouldn't that result in the channel being 0% / 1500us... until the user fixes it up? I guess UI wise, for colorLCD at least maybe it could be shown in the WARNING colour, to indicate an invalid source? Maybe B&W could show square brackets around invalid source lines, or even just blink invalid lines... something simple.

**Closed** 2024-01-05 09:16 UTC
Labels: enhancement ✨
