### ISSUE TITLE
t16s play track

### ISSUE THREAD

**Issue by stubugs** [EdgeTX/edgetx#2501] opened 2022-10-09 08:59 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

when doing a special function ie assigning  play track to switch when selecting the track you think nothings happeniing then tracks list loads 
long delay

### Expected Behavior

in 2.71 there was no delay

### Steps To Reproduce

trying to select playing track waiting to load list

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by pfeerick** [comment] 2022-10-09 09:46
Duplicate of #2284

**Closed by pfeerick** 2022-10-09 09:46 UTC
Labels: bug 🪲, triage
