### ISSUE TITLE
implement working " New Model Wizard "similar to OTX 2.3

### ISSUE THREAD

**Issue by Airfiddler** [EdgeTX/edgetx#1092] opened 2021-11-20 01:17 UTC
*Before suggesting a new feature here, please search the open issue if there is already a request for the feature.
You can add your comment there, or react so that we know know much interest there is in the feature request.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Airfiddler** [comment] 2021-11-20 01:19
This would reduce the learning curve for new ETX users and get them flying faster.

**Comment by raphaelcoeffic** [comment] 2021-11-21 21:10
I think there are two things here:
- There is nobody at the moment to maintain the Wizards
- We thought about having them in the "tools", as most people are annoyed when the Wizard is starting on every new model.
- Wizards are dull. The idea we had was to have different modes: "Starter", "Advanced" and "Expert". The starter would obviously have the Wizard starting and a simple menu without too many options. "Experts" would be like now with all the bells and whistles.

**Comment by Airfiddler** [comment] 2021-11-22 16:11
Good points. I would think the majority of ETX users would not fall into
the beginner category. I believe the category idea has tremendous merit, as
there would be something for everybody in ETX. The lifeblood of any pursuit
lies in attracting new users. The catagory option should probabily should
allow the noobs to turn off the feature as they progress into the advanced
catagory. Kudos to the developers on their amazing progress so far. Keep up
the great work.

**Comment by gagarinlg** [comment] 2021-11-26 07:55
is this a duplicate of #8 ?

**Comment by pfeerick** [comment] 2021-11-26 11:18
Yeah, I'll go with that... 

Duplicate of #8

**Closed by pfeerick** 2021-11-26 11:18 UTC
Labels: enhancement, lua-application
