### ISSUE TITLE
In the mixer menu, only the - sign is displayed at >-100%.

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#5036] opened 2024-05-19 16:58 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If the weighting is to display a value of -100%, there is not enough space so that only the - sign ap

### Expected Behavior

Please make the field larger

### Steps To Reproduce

1. go to the mixer settings
2. change the weighting to -100%
3. only the minus sign is displayed

### Version

2.10.0

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

[SCREENSHOTS.ZIP](https://github.com/EdgeTX/edgetx/files/15370140/SCREENSHOTS.ZIP)

**Comment by 3djc** [comment] 2024-05-19 17:26
Seems to be ok here

![image](https://github.com/EdgeTX/edgetx/assets/5167938/f8e82d3f-ee00-43c3-a941-23fd2d1d4599)

**Comment by philmoz** [comment] 2024-05-19 23:05
I can reproduce this in PR 5031 (fixed now); but not in 2.10 and 2.11 main branch.

@koaxheli If you are using a nightly build or the build from a PR please indicate this in the issue description.

**Comment by pfeerick** [comment] 2024-05-20 01:48
Screenshot attached looks more like from a nightly than 2.10  - notice the broader selection outline.

**Comment by koaxheli** [comment] 2024-05-20 11:45
The screenshot is from version 2.11.0
![screen-2024-05-20-120845](https://github.com/EdgeTX/edgetx/assets/92114465/21988c53-203b-4eff-b7be-b888beb74934)
![screen-2024-05-19-172405](https://github.com/EdgeTX/edgetx/assets/92114465/03d61b98-f37d-471d-aa6e-e1a22276ed6a)

**Comment by pfeerick** [comment] 2024-05-22 21:56
Thanks for confirming. You selected 2.10 rather than nightly/other hence the confusion there ;)

**Comment by philmoz** [comment] 2024-06-12 04:56
This is now fixed in 2.11.

**Closed** 2024-06-12 05:53 UTC
Labels: bug 🪲, triage
