### ISSUE TITLE
HelloRadioSky V16 - external Modul bay

### ISSUE THREAD

**Issue by Futaba-Guy** [EdgeTX/edgetx#5577] opened 2024-10-01 18:45 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I tried the 2.11- nightly at my HR V16pro. After flashing the external Modul HappyModel EX24pro doesn‘t get power. So the lua script eLRS didn‘t work. I open the Modul. Inside is an USB-Port. I powered the modul while sitting in the bay. It worked. So I flashed back to delivery state (2.10.1-selfbuild) and all worked fine again.

### Expected Behavior

That the modul gets (enough) power

### Steps To Reproduce

Everytime I put the modul in or fired up the transmiter it doesn‘t work with 2.11-nightly

### Version

Nightly (Please give date/commit below)

### Transmitter

HelloRadioSky V16pro

### Operating System (OS)

Windows

### OS Version

11

**Comment by pfeerick** [comment] 2024-12-05 02:48
Can you try again with a recently nightly. I am unable to reproduce this with latest nightly and RM Ranger ELRS module - module receives power and can be communicated with via ELRS Lua.

**Comment by Futaba-Guy** [comment] 2024-12-06 17:53
Hello Peter,I can’t find any issues with the nightly 366df608 anymore (I don’t know wich nightly this is). With today’s 3d1e7a9 is also all working.Kind regards ThomasAm 05.12.2024 um 03:48 schrieb Peter Feerick ***@***.***>:﻿
Can you try again with a recently nightly. I am unable to reproduce this with latest nightly and RM Ranger ELRS module - module receives power and can be communicated with via ELRS Lua.

**Comment by pfeerick** [comment] 2024-12-07 01:12
Thanks for checking, and for the update. I'll close the issue then as it looks to have been resolved.

**Closed by pfeerick** 2024-12-07 01:12 UTC
Labels: bug 🪲, triage
