### ISSUE TITLE
Trainer Slave not recognized in Master.

### ISSUE THREAD

**Issue by dwhacks** [EdgeTX/edgetx#1587] opened 2022-02-13 02:01 UTC
**Describe the bug**
x9 Lite does not detect when a slave trainer is plugged in (when configured as master)

**To Reproduce**
plug in a slave trainer with the x9 lite set to master

**Expected behavior**
Trainer connected status to be yes, and to accept a trainer

**General information**
 - EdgeTX version 2.5.0
 - Hardware Frsky x9 Lite

Here's the issue in OpenTX: https://github.com/opentx/opentx/issues/8670

**Comment by pfeerick** [comment] 2022-02-13 03:38
Is this fixed in OpenTX if you try a nightly? If so, it seems we made need following changes/fixes in our codebase also:
https://github.com/opentx/opentx/commit/2241c3f4ce3b0c6cd3fd41a45770c09ce3e75a7e (which appears to be what broke it in part)
https://github.com/opentx/opentx/pull/8811 (which appears to fix it for X7 Access and X9 Lite)

**Comment by CaleyD** [comment] 2022-02-13 04:57
May be completely unrelated, but I can’t get the zorro to recognize trainer port input either

**Comment by pfeerick** [comment] 2022-02-13 05:52
Most likely - I've not checked mine yet, but it probably suffers from the same trainer port socket issue as the TX12 and TX16S, where you either needed a specific extended plug, or to modify the socket to accept a normal plug.

**Comment by dwhacks** [comment] 2022-02-24 01:48
I haven't had a chance to test it (not a big fan of swapping firmware's back and forth) but apparently it has been fixed in opentx with https://github.com/opentx/opentx/pull/8811

**Comment by P-I-Engineer** [comment] 2022-03-11 19:32
was going to post an issue, but i'm having same problem. Can confirm that opentx 2.3.15 nightly the issue is resolved.

**Comment by pfeerick** [comment] 2022-03-12 02:43
Excellent. Thanks for that. I'll put a PR together that brings that across then. I'll call for testers again for the X9 Lite as I will be able to test it for the X9D+2019, but not the X9 Lite (or X7 Access).

**Comment by dwhacks** [comment] 2022-03-12 03:03
Perfect, I am ready to test it out on x9 lite!

**Closed** 2022-03-18 08:57 UTC
