### ISSUE TITLE
Edge parameter change after edit and exit.

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#3035] opened 2023-01-14 14:37 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If in edge command you edit the delay time and exit with for instance [1.5:<<] the second parameter reverts to "39.5" [1.5:39.5]. You have to reselect the [<<] parameter before exiting or come back in and change back afterwards. It does work but it is strange that you have to revisit this and check that it has remained as set.

### Expected Behavior

Change the parameter selected in edge and expect no change to second parameter when exiting.

### Steps To Reproduce

in 2.9.0 nighltly but expect is also in be 2.8.0

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12

### Anything else?

14-01-23
![screen-2023-01-14-145244](https://user-images.githubusercontent.com/56512603/212478250-a699124f-af4d-4750-ae61-5799f539007a.png)
Before edit
![screen-2023-01-14-145316](https://user-images.githubusercontent.com/56512603/212478280-d63c0518-dea2-4449-ac61-bda52a25d474.png)
After editing and exiting "<<" changes to "39.5" should have remained "<<" and believe should not have to reselect or revisit and change after exit.

**Comment by philmoz** [comment] 2023-01-14 20:00
This is covered in issue #3022 
It will be fixed when PR #3026 is merged.

**Comment by pfeerick** [comment] 2023-01-15 09:28
Duplicate of #3022

**Closed by pfeerick** 2023-01-15 09:28 UTC
Labels: bug 🪲, triage

**Comment by Kevltan** [comment] 2023-01-15 23:22
Have you updated this issue in the latest nightly as the same is true if it
has been?

**Comment by Kevltan** [comment] 2023-01-15 23:31
I don't think it is the same issue 😕

**Comment by philmoz** [comment] 2023-01-16 00:01
My apologies - this is not the same issue as #3022 and it should be re-opened.

**Comment by Kevltan** [comment] 2023-01-16 00:30
Ok, thanks. Will re-open👍

**Comment by Kevltan** [comment] 2023-01-16 00:32
How do I re-open?

**Comment by pfeerick** [comment] 2023-01-17 05:05
My apologies also - I missed that it was only on closing the edit window rather than changing when you changed model/power cycled. 

There should be a button down the buttom next to the comment button, or simply wait for someone to respond to the issue and re-open it. 
![image](https://user-images.githubusercontent.com/5500713/212814357-ea548b4d-f406-4351-be00-be106536ab44.png)
