### ISSUE TITLE
Companion 2.10.1 can't write *.etx file to "my documents"

### ISSUE THREAD

**Issue by Wubbo** [EdgeTX/edgetx#5142] opened 2024-06-09 12:49 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

After I download the settings  from transmitter, I want to save the *.etx file to "...\Documents\EdgeTX\TX16S".
It showes the message "file not found".
Saving to the desktop works fine though.
If I try to save it to an existing file in my documents it apears to work fine, but it does not overwrite the file.
With Companion 2.8 it worked as expexted.
With Companion 2.10.1 I have these problems.
After I saved the file to the desktop I can move it to "My documents" without problem.

### Expected Behavior

Normal safe a file to My documents

### Steps To Reproduce

1. Read models from radio
2. File, Safe to My documents
3. See the Error

### Version

2.10.1

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

10 pro built 19045.4412 64bit 

### Anything else?

![EdgeTX Error](https://github.com/EdgeTX/edgetx/assets/59174594/e9b5f0aa-98ab-42dc-a5ff-ac6827da78b1)

**Comment by 3djc** [comment] 2024-06-09 13:26
Works fine here. Maybe a doggy permission issue ?

**Comment by Wubbo** [comment] 2024-06-09 19:07
That was my first thought, I changed some security setting with no luck.
The most strange is that when I save the file it comes with "can not find file", as if I want to open the file.

**Comment by elecpower** [comment] 2024-06-10 07:35
Works for me too.
Though you are using a Windows registry redirection to translate This PC -> Documents to a real drive and folder.
Try saving to the real path and see if that works.
The 'file no found' is a library message and takes no notice of the action. Nothing we can do.

**Comment by Wubbo** [comment] 2024-06-12 14:53
Thank you for your support.
![Naamloos](https://github.com/EdgeTX/edgetx/assets/59174594/230a4dd7-7b93-4019-b172-294101ee4e9e)
It wil not save to file in any folder in "Documents".

**Comment by elecpower** [comment] 2024-06-12 19:58
I'm leaning the same way as @3djc and its some sort of permissions issue since you can write elsewhere in the file system. Either that or an anti virus issue though that should stop saving anywhere in the file system.
If the folder was transferred from another Windows machine there can be permission artefacts.

**Comment by pfeerick** [comment] 2024-06-12 23:51
I can't reproduce this on Windows 11 with Companion 2.10.1... saving to `Documents` works just fine. However, I don't have Onedrive configured to **_redirect_** all saves to the cloud, which is another possible cause for the problem.

**Comment by Wubbo** [comment] 2024-06-13 18:22
@Pfeerick, i don't use Onedrive, so that can be ruled out.

**Comment by Wubbo** [comment] 2024-06-13 18:32
The folder was not moved from an other machine, the problem occurred first when I switched from companion 2.8 to 2.10. 

For now I moved the Documents folder to the root of C:, now it works again, there is only 1 user on that computer so this will not cause a problem.

Thank you for your support.

**Comment by pfeerick** [comment] 2024-06-13 21:44
So what is drawing the green overlay icons on the files? Dropbox? Google Drive? Something else?

**Comment by Wubbo** [comment] 2024-06-13 22:16
That is from Synology drive, it makes a backup to my nas.
The green checkmark shows it has backuped the file.
I also checked with Synology drive disabled, with no effect.
But now I have moved the Documents folder to C:, I also changed the the Synology source to this folder.
Now it works fine.

**Comment by pfeerick** [comment] 2024-06-13 23:11
Ok, thanks for that. Given three of us can't reproduce this on Windows, that still pretty much just leaves some odd anti-virus (i.e. I think Defender has the option to "harden" access to some folders) or permissions issue with the Documents folder. Have you tried running Companion with administrative permissions to see if it can write to the Documents folder then? I'm away from computer atm, but usually you just right click on an apps icon and you'll get "Run as Administrator" or similar option in the list.

**Comment by pfeerick** [comment] 2024-06-14 01:15
This post shows the option I was thinking of in Windows Defender... https://answers.microsoft.com/en-us/msoffice/forum/all/cant-save-file-to-onedrive-documents-folder/dc9674ef-b65d-4462-9695-384024883609

**Comment by Wubbo** [comment] 2024-06-15 23:53
Thank you Pfeerick, yes I did run as administrator, even in compatibilty mode with windows 8. but nothing changes.
I did switch off the protected folders. That works !!!!
The strange thing is that only companion 2.10 had this problem not 2.8.
But I am happy for this solution.
Thank you Pfeerick.

**Comment by pfeerick** [comment] 2024-07-18 02:39
I'm going to close this is issue due to it being related to Microsoft Defender Antivirus being stupid, rather than a bug on our side... If it gets it into its head to just start blocking stuff, there is nothing we can do about that - that is out of our control.

**Closed by pfeerick** 2024-07-18 02:39 UTC
Labels: bug 🪲, companion, triage
