### ISSUE TITLE
An error occurred while updating the Internal multimodule for the TX12 MarkII

### ISSUE THREAD

**Issue by zyren** [EdgeTX/edgetx#2313] opened 2022-09-13 09:24 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

*

### Expected Behavior

*

### Steps To Reproduce

The radio will restart when the Internal Multimodule is updating.
When the External Multimodule is updating, a message pops up: FW update error, Device not responding.
I've tried turning Internal RF/External RF on or off, no matter what, it's the same thing.

Tansmitter: TX12 MarkII
Firmware version: Nightly 1c71562

### Version

Nightly (1c71562)

### Transmitter

RadioMaster  TX12MK2

**Comment by pfeerick** [comment] 2022-09-13 09:29
Duplicate of #2310. A fix is in the process of being tested so should be out soon.

**Closed by pfeerick** 2022-09-13 09:29 UTC
Labels: bug 🪲, triage
