### ISSUE TITLE
compagnon 2.8.2 simulator crash

### ISSUE THREAD

**Issue by LS-67** [EdgeTX/edgetx#3469] opened 2023-04-12 14:28 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When choosing "simulation" for a model in compagnon 2.8.2, ...compagnon crash

### Expected Behavior

Compagnon doesn't crash when choosing simulation

### Steps To Reproduce

1) Open Compagnon 2.8.2
2) Select a model.
3) Double click on it
4) Choose "simulation"
and ...compagnon crash 

### Version

2.8.2

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

10

**Comment by FearlessFlyer** [comment] 2023-04-12 16:06
Same here on Windows 7 Pro.
I have gone back to the previous version, wich runs well.

**Comment by mha1** [comment] 2023-04-12 18:43
Does the active model have MPM (Multi) selected as internal module? If yes this is fixed with https://github.com/EdgeTX/edgetx/pull/3426 and will be part of 2.8.3.

**Comment by LS-67** [comment] 2023-04-13 04:01
Yes, the model has MPM selected. Thank's

**Comment by pfeerick** [comment] 2023-04-13 04:08
Duplicate of #3469

**Closed by pfeerick** 2023-04-13 04:08 UTC
Labels: bug 🪲
